/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  models: [],
  defaultModelId: "",
  insertMode: "cursor",
  systemInstruction: ""
};
var AISettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Margin \u8BBE\u7F6E" });
    containerEl.createEl("h3", { text: "\u6DFB\u52A0\u6A21\u578B" });
    containerEl.createEl("p", {
      cls: "ai-set-hint",
      text: "\u6A21\u578B\u540D\u79F0\u586B\u5199\u4F60\u60F3\u8981\u7684\u578B\u53F7\uFF08\u5982 gemini-3.5-flash\uFF09\uFF0CAPI Key \u4ECE Google AI Studio \u83B7\u53D6\u3002\u53EF\u6DFB\u52A0\u591A\u4E2A\u5E76\u968F\u65F6\u5207\u6362\u3002"
    });
    const addWrap = containerEl.createDiv({ cls: "ai-set-add" });
    const nameInput = addWrap.createEl("input", {
      cls: "ai-set-input",
      placeholder: "\u6A21\u578B\u540D\u79F0\uFF0C\u5982 gemini-3.5-flash"
    });
    const keyInput = addWrap.createEl("input", {
      cls: "ai-set-input",
      placeholder: "API Key",
      type: "password"
    });
    const addBtn = addWrap.createEl("button", {
      cls: "ai-set-add-btn mod-cta",
      text: "\u6DFB\u52A0\u6A21\u578B"
    });
    addBtn.addEventListener("click", async () => {
      const name = nameInput.value.trim();
      const key = keyInput.value.trim();
      if (!name || !key) {
        new import_obsidian.Notice("\u8BF7\u586B\u5199\u6A21\u578B\u540D\u79F0\u548C API Key");
        return;
      }
      const model = {
        id: "m_" + Date.now().toString(36) + Math.random().toString(36).slice(2, 6),
        name,
        provider: "gemini",
        apiKey: key
      };
      this.plugin.settings.models.push(model);
      if (!this.plugin.settings.defaultModelId) {
        this.plugin.settings.defaultModelId = model.id;
      }
      await this.plugin.saveSettings();
      this.display();
    });
    containerEl.createEl("h3", { text: "\u5DF2\u6DFB\u52A0\u6A21\u578B" });
    if (this.plugin.settings.models.length === 0) {
      containerEl.createEl("p", {
        cls: "ai-set-empty",
        text: "\u8FD8\u6CA1\u6709\u6A21\u578B\uFF0C\u5148\u5728\u4E0A\u65B9\u6DFB\u52A0\u3002"
      });
    }
    this.plugin.settings.models.forEach((m) => {
      const row = containerEl.createDiv({ cls: "ai-set-model-row" });
      row.createEl("span", { cls: "ai-set-model-name", text: m.name });
      row.createEl("span", { cls: "ai-set-model-provider", text: m.provider });
      const isDefault = this.plugin.settings.defaultModelId === m.id;
      const def = row.createEl("button", {
        cls: "ai-set-model-default" + (isDefault ? " is-default" : ""),
        text: isDefault ? "\u9ED8\u8BA4 \u2713" : "\u8BBE\u4E3A\u9ED8\u8BA4"
      });
      def.addEventListener("click", async () => {
        this.plugin.settings.defaultModelId = m.id;
        await this.plugin.saveSettings();
        this.display();
      });
      const del = row.createEl("button", {
        cls: "ai-set-model-del",
        text: "\u5220\u9664"
      });
      del.addEventListener("click", async () => {
        var _a, _b;
        this.plugin.settings.models = this.plugin.settings.models.filter(
          (x) => x.id !== m.id
        );
        if (this.plugin.settings.defaultModelId === m.id) {
          this.plugin.settings.defaultModelId = (_b = (_a = this.plugin.settings.models[0]) == null ? void 0 : _a.id) != null ? _b : "";
        }
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u6A21\u578B").setDesc("\u65B0\u5BF9\u8BDD / \u5212\u8BCD\u4F7F\u7528\u7684\u9ED8\u8BA4\u6A21\u578B").addDropdown((d) => {
      this.plugin.settings.models.forEach((m) => d.addOption(m.id, m.name));
      d.setValue(this.plugin.settings.defaultModelId);
      d.onChange(async (v) => {
        this.plugin.settings.defaultModelId = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u5212\u8BCD\u7ED3\u679C\u63D2\u5165\u4F4D\u7F6E").setDesc("\u5728\u5212\u8BCD\u60AC\u6D6E\u6846\u70B9\u51FB\u300C\u63D2\u5165\u300D\u65F6\u7684\u843D\u70B9").addDropdown((d) => {
      d.addOption("cursor", "\u5149\u6807\u5904");
      d.addOption("after", "\u9009\u533A\u4E4B\u540E");
      d.setValue(this.plugin.settings.insertMode);
      d.onChange(async (v) => {
        this.plugin.settings.insertMode = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u7CFB\u7EDF\u6307\u4EE4\uFF08\u53EF\u9009\uFF09").setDesc("\u8FFD\u52A0\u7ED9\u6A21\u578B\u7684\u5168\u5C40\u8BBE\u5B9A\uFF0C\u4F8B\u5982\u201C\u7528\u7B80\u6D01\u4E2D\u6587\u56DE\u7B54\u201D").addTextArea((t) => {
      t.setValue(this.plugin.settings.systemInstruction);
      t.onChange(async (v) => {
        this.plugin.settings.systemInstruction = v;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/views/chatView.ts
var import_obsidian2 = require("obsidian");

// src/llm/gemini.ts
var GeminiProvider = class {
  constructor() {
    __publicField(this, "id", "gemini");
  }
  async chat(model, messages, cb, opts) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m;
    const base = model.baseUrl || "https://generativelanguage.googleapis.com/v1beta";
    const url = `${base}/models/${encodeURIComponent(
      model.name
    )}:streamGenerateContent?alt=sse&key=${model.apiKey}`;
    const contents = messages.map((m) => ({
      role: m.role === "model" ? "model" : "user",
      parts: [{ text: m.content }]
    }));
    const body = { contents };
    if ((opts == null ? void 0 : opts.systemInstruction) && opts.systemInstruction.trim()) {
      body.systemInstruction = {
        parts: [{ text: opts.systemInstruction }]
      };
    }
    let res;
    try {
      res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
    } catch (e) {
      (_a = cb.onError) == null ? void 0 : _a.call(cb, new Error("\u7F51\u7EDC\u8BF7\u6C42\u5931\u8D25\uFF1A" + e.message));
      return;
    }
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      (_b = cb.onError) == null ? void 0 : _b.call(cb, new Error(`Gemini API ${res.status}: ${text.slice(0, 300)}`));
      return;
    }
    if (!res.body) {
      (_c = cb.onError) == null ? void 0 : _c.call(cb, new Error("\u54CD\u5E94\u4E3A\u7A7A"));
      return;
    }
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buf = "";
    let usage = null;
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buf += decoder.decode(value, { stream: true });
        const lines = buf.split("\n");
        buf = lines.pop() || "";
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed.startsWith("data:")) continue;
          const json = trimmed.slice(5).trim();
          if (!json || json === "[DONE]") continue;
          try {
            const data = JSON.parse(json);
            const text = ((_g = (_f = (_e = (_d = data.candidates) == null ? void 0 : _d[0]) == null ? void 0 : _e.content) == null ? void 0 : _f.parts) == null ? void 0 : _g.map((p) => p.text || "").join("")) || "";
            if (text) (_h = cb.onToken) == null ? void 0 : _h.call(cb, text);
            if (data.usageMetadata) {
              usage = {
                promptTokens: (_i = data.usageMetadata.promptTokenCount) != null ? _i : 0,
                completionTokens: (_j = data.usageMetadata.candidatesTokenCount) != null ? _j : 0,
                totalTokens: (_k = data.usageMetadata.totalTokenCount) != null ? _k : 0
              };
            }
          } catch (e) {
          }
        }
      }
    } catch (e) {
      (_l = cb.onError) == null ? void 0 : _l.call(cb, new Error("\u8BFB\u53D6\u54CD\u5E94\u5931\u8D25\uFF1A" + e.message));
      return;
    }
    (_m = cb.onDone) == null ? void 0 : _m.call(cb, usage);
  }
};

// src/llm/index.ts
var providers = {
  gemini: new GeminiProvider()
};
function getProvider(id) {
  const p = providers[id];
  if (!p) throw new Error(`\u672A\u77E5\u7684\u4F9B\u5E94\u5546\uFF1A${id}`);
  return p;
}

// src/views/chatView.ts
var VIEW_TYPE_CHAT = "margin-chat";
var ChatView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    __publicField(this, "messages", []);
    __publicField(this, "messagesEl");
    __publicField(this, "inputEl");
    __publicField(this, "modelSelect");
    __publicField(this, "usageEl");
    __publicField(this, "busy", false);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "AI Chat";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  /** 设置变更后刷新模型下拉 */
  refreshModels() {
    if (!this.modelSelect) return;
    this.populateModels();
  }
  currentModel() {
    var _a;
    const id = (_a = this.modelSelect) == null ? void 0 : _a.value;
    return this.plugin.settings.models.find((m) => m.id === id) || this.plugin.settings.models[0];
  }
  populateModels() {
    this.modelSelect.empty();
    for (const m of this.plugin.settings.models) {
      this.modelSelect.createEl("option", { text: m.name, value: m.id });
    }
    if (this.plugin.settings.defaultModelId) {
      this.modelSelect.value = this.plugin.settings.defaultModelId;
    }
  }
  render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("ai-chat");
    const header = root.createDiv({ cls: "ai-chat-header" });
    this.modelSelect = header.createEl("select", {
      cls: "ai-chat-model-select dropdown"
    });
    this.populateModels();
    const clearBtn = header.createEl("button", {
      cls: "ai-chat-clear",
      text: "\u6E05\u7A7A"
    });
    clearBtn.addEventListener("click", () => {
      this.messages = [];
      this.renderMessages();
    });
    this.messagesEl = root.createDiv({ cls: "ai-chat-messages" });
    this.usageEl = root.createDiv({ cls: "ai-chat-usage" });
    const inputWrap = root.createDiv({ cls: "ai-chat-input-wrap" });
    this.inputEl = inputWrap.createEl("textarea", {
      cls: "ai-chat-input",
      placeholder: "\u8F93\u5165\u6D88\u606F\uFF0CEnter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C"
    });
    const sendBtn = inputWrap.createEl("button", {
      cls: "ai-chat-send mod-cta",
      text: "\u53D1\u9001"
    });
    sendBtn.addEventListener("click", () => this.send());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.send();
      }
    });
    this.renderMessages();
  }
  renderMessages() {
    this.messagesEl.empty();
    for (const m of this.messages) {
      const bubble = this.messagesEl.createDiv({
        cls: `ai-msg ai-msg-${m.role}`
      });
      bubble.createEl("div", {
        cls: "ai-msg-role",
        text: m.role === "user" ? "\u4F60" : "AI"
      });
      bubble.createEl("div", { cls: "ai-msg-content", text: m.content });
    }
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  async send() {
    const text = this.inputEl.value.trim();
    if (!text || this.busy) return;
    const model = this.currentModel();
    if (!model) {
      new import_obsidian2.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u6DFB\u52A0 Gemini \u6A21\u578B");
      return;
    }
    this.inputEl.value = "";
    this.messages.push({ role: "user", content: text });
    this.renderMessages();
    this.busy = true;
    const aiBubble = this.messagesEl.createDiv({ cls: "ai-msg ai-msg-model" });
    aiBubble.createEl("div", { cls: "ai-msg-role", text: "AI" });
    const contentEl = aiBubble.createEl("div", {
      cls: "ai-msg-content",
      text: ""
    });
    let acc = "";
    const provider = getProvider(model.provider);
    try {
      await provider.chat(
        model,
        this.messages,
        {
          onToken: (t) => {
            acc += t;
            contentEl.setText(acc);
            this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
          },
          onDone: (usage) => {
            this.messages.push({ role: "model", content: acc });
            this.showUsage(usage);
          },
          onError: (e) => {
            new import_obsidian2.Notice("\u9519\u8BEF\uFF1A" + e.message);
            contentEl.setText("\u26A0\uFE0F " + e.message);
          }
        },
        { systemInstruction: this.plugin.settings.systemInstruction }
      );
    } finally {
      this.busy = false;
    }
  }
  showUsage(u) {
    if (!u) {
      this.usageEl.setText("");
      return;
    }
    this.usageEl.setText(
      `\u672C\u6B21\u7528\u91CF \u2014 \u63D0\u793A ${u.promptTokens} \xB7 \u8865\u5168 ${u.completionTokens} \xB7 \u603B\u8BA1 ${u.totalTokens} tokens`
    );
  }
};

// src/selection/popover.ts
var import_obsidian3 = require("obsidian");
var SelectionPopover = class {
  constructor(plugin, editor, selected) {
    __publicField(this, "plugin");
    __publicField(this, "editor");
    __publicField(this, "selected");
    __publicField(this, "messages", []);
    __publicField(this, "from");
    __publicField(this, "to");
    __publicField(this, "root");
    __publicField(this, "messagesEl");
    __publicField(this, "inputEl");
    __publicField(this, "actionsEl");
    __publicField(this, "usageEl");
    __publicField(this, "lastResult", "");
    __publicField(this, "busy", false);
    __publicField(this, "onOutside", (e) => {
      if (this.root && !this.root.contains(e.target)) {
        this.close();
      }
    });
    this.plugin = plugin;
    this.editor = editor;
    this.selected = selected;
    this.from = editor.getCursor("from");
    this.to = editor.getCursor("to");
  }
  open() {
    const root = document.createElement("div");
    root.className = "ai-popover";
    root.addEventListener("click", (e) => e.stopPropagation());
    const sel = window.getSelection();
    let top = 120;
    let left = 120;
    if (sel && sel.rangeCount > 0) {
      const r = sel.getRangeAt(0).getBoundingClientRect();
      top = r.bottom + 6;
      left = r.left;
    }
    top = Math.min(top, window.innerHeight - 340);
    left = Math.max(8, Math.min(left, window.innerWidth - 372));
    root.style.top = `${top}px`;
    root.style.left = `${left}px`;
    const header = root.createDiv({ cls: "ai-popover-header" });
    header.createSpan({ cls: "ai-popover-title", text: "AI \u5BF9\u8BDD" });
    const close = header.createSpan({ cls: "ai-popover-close", text: "\xD7" });
    close.addEventListener("click", () => this.close());
    const ctx = root.createDiv({ cls: "ai-popover-ctx" });
    ctx.createSpan({ text: "\u9009\u533A\uFF1A" });
    ctx.createSpan({
      cls: "ai-popover-ctx-text",
      text: this.selected.slice(0, 120) + (this.selected.length > 120 ? "\u2026" : "")
    });
    this.messagesEl = root.createDiv({ cls: "ai-popover-messages" });
    this.usageEl = root.createDiv({ cls: "ai-popover-usage" });
    this.actionsEl = root.createDiv({ cls: "ai-popover-actions" });
    this.renderActions();
    const inputWrap = root.createDiv({ cls: "ai-popover-input-wrap" });
    this.inputEl = inputWrap.createEl("textarea", {
      cls: "ai-popover-input",
      placeholder: "\u8F93\u5165\u6307\u4EE4\uFF0C\u4F8B\u5982\uFF1A\u89E3\u91CA\u8FD9\u6BB5 / \u6539\u5199\u6210\u53E3\u8BED / \u7FFB\u8BD1\u4E3A\u82F1\u6587"
    });
    const send = inputWrap.createEl("button", {
      cls: "ai-popover-send mod-cta",
      text: "\u53D1\u9001"
    });
    send.addEventListener("click", () => this.send());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.send();
      }
    });
    document.body.appendChild(root);
    this.root = root;
    this.inputEl.focus();
    setTimeout(() => {
      document.addEventListener("click", this.onOutside, true);
    }, 0);
  }
  close() {
    var _a;
    document.removeEventListener("click", this.onOutside, true);
    (_a = this.root) == null ? void 0 : _a.remove();
    this.root = void 0;
  }
  renderActions() {
    if (!this.actionsEl) return;
    this.actionsEl.empty();
    if (!this.lastResult) {
      this.actionsEl.setText("");
      return;
    }
    const copy = this.actionsEl.createEl("button", {
      cls: "ai-popover-btn",
      text: "\u590D\u5236"
    });
    copy.addEventListener("click", () => {
      navigator.clipboard.writeText(this.lastResult);
      new import_obsidian3.Notice("\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
    });
    const insert = this.actionsEl.createEl("button", {
      cls: "ai-popover-btn",
      text: "\u63D2\u5165\u5149\u6807\u5904"
    });
    insert.addEventListener("click", () => {
      this.editor.replaceRange(this.lastResult, this.editor.getCursor());
      new import_obsidian3.Notice("\u5DF2\u63D2\u5165\u5230\u5149\u6807\u5904");
    });
    const cover = this.actionsEl.createEl("button", {
      cls: "ai-popover-btn mod-warning",
      text: "\u8986\u76D6\u9009\u533A"
    });
    cover.addEventListener("click", () => {
      this.editor.replaceRange(this.lastResult, this.from, this.to);
      new import_obsidian3.Notice("\u5DF2\u8986\u76D6\u9009\u533A");
    });
    const cont = this.actionsEl.createEl("button", {
      cls: "ai-popover-btn",
      text: "\u7EE7\u7EED\u5BF9\u8BDD"
    });
    cont.addEventListener("click", () => {
      var _a;
      return (_a = this.inputEl) == null ? void 0 : _a.focus();
    });
  }
  async send() {
    var _a;
    const text = (_a = this.inputEl) == null ? void 0 : _a.value.trim();
    if (!text || this.busy) return;
    const model = this.plugin.settings.models.find(
      (m) => m.id === this.plugin.settings.defaultModelId
    ) || this.plugin.settings.models[0];
    if (!model) {
      new import_obsidian3.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u6DFB\u52A0 Gemini \u6A21\u578B");
      return;
    }
    if (this.messages.length === 0) {
      this.messages.push({
        role: "user",
        content: `\u4EE5\u4E0B\u662F\u9009\u4E2D\u7684\u6587\u672C\uFF1A
"""
${this.selected}
"""

\u8BF7\u57FA\u4E8E\u4E0A\u8FF0\u6587\u672C\u56DE\u7B54\u6211\u7684\u95EE\u9898\uFF1A${text}`
      });
    } else {
      this.messages.push({ role: "user", content: text });
    }
    if (this.inputEl) this.inputEl.value = "";
    this.busy = true;
    const aiBubble = this.messagesEl.createDiv({
      cls: "ai-popover-msg ai-popover-msg-model"
    });
    const contentEl = aiBubble.createEl("div", {
      cls: "ai-popover-msg-content",
      text: ""
    });
    let acc = "";
    const provider = getProvider(model.provider);
    try {
      await provider.chat(
        model,
        this.messages,
        {
          onToken: (t) => {
            acc += t;
            contentEl.setText(acc);
            this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
          },
          onDone: (u) => {
            this.messages.push({ role: "model", content: acc });
            this.lastResult = acc;
            this.renderActions();
            this.renderUsage(u);
          },
          onError: (e) => {
            new import_obsidian3.Notice("\u9519\u8BEF\uFF1A" + e.message);
            contentEl.setText("\u26A0\uFE0F " + e.message);
          }
        },
        { systemInstruction: this.plugin.settings.systemInstruction }
      );
    } finally {
      this.busy = false;
    }
  }
  renderUsage(u) {
    if (!u || !this.usageEl) return;
    this.usageEl.setText(
      `\u7528\u91CF: \u63D0\u793A ${u.promptTokens} \xB7 \u8865\u5168 ${u.completionTokens} \xB7 \u603B\u8BA1 ${u.totalTokens}`
    );
  }
};

// src/main.ts
var AIPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_CHAT, (leaf) => new ChatView(leaf, this));
    this.addRibbonIcon("message-square", "\u6253\u5F00 AI Chat", () => {
      this.activateChat();
    });
    this.addCommand({
      id: "open-ai-chat",
      name: "\u6253\u5F00 AI Chat",
      callback: () => this.activateChat()
    });
    this.registerEvent(
      this.app.workspace.on(
        "editor-menu",
        (menu, editor) => {
          const selected = editor.getSelection();
          if (!selected) return;
          menu.addItem((item) => {
            item.setTitle("AI \u5BF9\u8BDD").setIcon("sparkles").onClick(() => {
              const popover = new SelectionPopover(
                this,
                editor,
                selected
              );
              popover.open();
            });
          });
        }
      )
    );
    this.addSettingTab(new AISettingsTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("margin:settings-changed", () => {
        const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
        if (leaf) leaf.view.refreshModels();
      })
    );
  }
  onunload() {
  }
  async activateChat() {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
    }
    this.app.workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.app.workspace.trigger("margin:settings-changed");
  }
};
