/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  models: [],
  defaultModelId: "",
  systemInstruction: ""
};
function createKeyInput(container, value = "") {
  const wrap = container.createDiv({ cls: "ai-set-key-wrap" });
  const input = wrap.createEl("input", {
    cls: "ai-set-input ai-set-key-input",
    placeholder: "API Key",
    type: "password",
    value
  });
  const eye = wrap.createEl("button", {
    cls: "ai-set-eye",
    text: "\u{1F441}",
    attr: { type: "button", title: "\u663E\u793A / \u9690\u85CF" }
  });
  eye.addEventListener("click", () => {
    const show = input.type === "password";
    input.type = show ? "text" : "password";
    eye.setText(show ? "\u{1F648}" : "\u{1F441}");
  });
  return input;
}
var AISettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("ai-set");
    containerEl.createEl("h2", { text: "Margin \u8BBE\u7F6E" });
    this.renderAddModel(containerEl);
    this.renderModelList(containerEl);
    this.renderGeneral(containerEl);
  }
  /** 添加模型：名称 + Key（带眼睛）+ 添加按钮 */
  renderAddModel(containerEl) {
    const card = containerEl.createDiv({ cls: "ai-set-card" });
    card.createEl("h3", { text: "\u6DFB\u52A0\u6A21\u578B" });
    card.createEl("p", {
      cls: "ai-set-hint",
      text: "\u6A21\u578B\u540D\u79F0\u586B\u4F60\u60F3\u8981\u7684\u578B\u53F7\uFF08\u5982 gemini-3.5-flash\uFF09\uFF0CAPI Key \u4ECE Google AI Studio \u83B7\u53D6\u3002\u53EF\u6DFB\u52A0\u591A\u4E2A\u5E76\u968F\u65F6\u5207\u6362\u3002"
    });
    const addWrap = card.createDiv({ cls: "ai-set-add" });
    const nameInput = addWrap.createEl("input", {
      cls: "ai-set-input",
      placeholder: "\u6A21\u578B\u540D\u79F0\uFF0C\u5982 gemini-3.5-flash"
    });
    const keyInput = createKeyInput(addWrap);
    const addBtn = addWrap.createEl("button", {
      cls: "ai-set-add-btn mod-cta",
      text: "\u6DFB\u52A0\u6A21\u578B"
    });
    addBtn.addEventListener("click", async () => {
      const name = nameInput.value.trim();
      const key = keyInput.value.trim();
      if (!name || !key) {
        new import_obsidian.Notice("\u8BF7\u586B\u5199\u6A21\u578B\u540D\u79F0\u548C API Key");
        return;
      }
      const model = {
        id: "m_" + Date.now().toString(36) + Math.random().toString(36).slice(2, 6),
        name,
        provider: "gemini",
        apiKey: key
      };
      this.plugin.settings.models.push(model);
      if (!this.plugin.settings.defaultModelId) {
        this.plugin.settings.defaultModelId = model.id;
      }
      await this.plugin.saveSettings();
      this.display();
    });
  }
  /** 模型列表：名称 / 供应商 + 设为默认 / 修改 / 删除 */
  renderModelList(containerEl) {
    const card = containerEl.createDiv({ cls: "ai-set-card" });
    card.createEl("h3", { text: "\u5DF2\u6DFB\u52A0\u6A21\u578B" });
    if (this.plugin.settings.models.length === 0) {
      card.createEl("p", {
        cls: "ai-set-empty",
        text: "\u8FD8\u6CA1\u6709\u6A21\u578B\uFF0C\u5148\u5728\u4E0A\u65B9\u6DFB\u52A0\u3002"
      });
      return;
    }
    this.plugin.settings.models.forEach((m) => {
      const row = card.createDiv({ cls: "ai-set-model-row" });
      const info = row.createDiv({ cls: "ai-set-model-info" });
      info.createEl("span", { cls: "ai-set-model-name", text: m.name });
      info.createEl("span", { cls: "ai-set-model-provider", text: m.provider });
      const actions = row.createDiv({ cls: "ai-set-model-actions" });
      const isDefault = this.plugin.settings.defaultModelId === m.id;
      const def = actions.createEl("button", {
        cls: "ai-set-model-btn" + (isDefault ? " is-default" : ""),
        text: isDefault ? "\u9ED8\u8BA4 \u2713" : "\u8BBE\u4E3A\u9ED8\u8BA4"
      });
      def.addEventListener("click", async () => {
        this.plugin.settings.defaultModelId = m.id;
        await this.plugin.saveSettings();
        this.display();
      });
      const edit = actions.createEl("button", {
        cls: "ai-set-model-btn",
        text: "\u4FEE\u6539"
      });
      edit.addEventListener("click", () => this.renderEditForm(row, m));
      const del = actions.createEl("button", {
        cls: "ai-set-model-btn ai-set-model-del",
        text: "\u5220\u9664"
      });
      del.addEventListener("click", async () => {
        var _a, _b;
        this.plugin.settings.models = this.plugin.settings.models.filter(
          (x) => x.id !== m.id
        );
        if (this.plugin.settings.defaultModelId === m.id) {
          this.plugin.settings.defaultModelId = (_b = (_a = this.plugin.settings.models[0]) == null ? void 0 : _a.id) != null ? _b : "";
        }
        await this.plugin.saveSettings();
        this.display();
      });
    });
  }
  /** 行内编辑模型：名称 / Key（带眼睛）/ baseUrl + 保存 / 取消 */
  renderEditForm(row, m) {
    var _a;
    row.empty();
    row.addClass("is-editing");
    const nameInput = row.createEl("input", {
      cls: "ai-set-input",
      value: m.name,
      placeholder: "\u6A21\u578B\u540D\u79F0"
    });
    const keyInput = createKeyInput(row, m.apiKey);
    const urlInput = row.createEl("input", {
      cls: "ai-set-input",
      value: (_a = m.baseUrl) != null ? _a : "",
      placeholder: "base URL\uFF08\u53EF\u9009\uFF0C\u4EE3\u7406 / \u7F51\u5173\u7528\uFF09"
    });
    const btnWrap = row.createDiv({ cls: "ai-set-model-actions" });
    const save = btnWrap.createEl("button", {
      cls: "ai-set-model-btn mod-cta",
      text: "\u4FDD\u5B58"
    });
    save.addEventListener("click", async () => {
      m.name = nameInput.value.trim() || m.name;
      m.apiKey = keyInput.value.trim() || m.apiKey;
      m.baseUrl = urlInput.value.trim() || void 0;
      await this.plugin.saveSettings();
      this.display();
    });
    const cancel = btnWrap.createEl("button", {
      cls: "ai-set-model-btn",
      text: "\u53D6\u6D88"
    });
    cancel.addEventListener("click", () => this.display());
  }
  /** 默认模型下拉 + 系统指令 */
  renderGeneral(containerEl) {
    const card = containerEl.createDiv({ cls: "ai-set-card" });
    new import_obsidian.Setting(card).setName("\u9ED8\u8BA4\u6A21\u578B").setDesc("\u65B0\u5BF9\u8BDD / \u5212\u8BCD\u4F7F\u7528\u7684\u9ED8\u8BA4\u6A21\u578B").addDropdown((d) => {
      this.plugin.settings.models.forEach((m) => d.addOption(m.id, m.name));
      d.setValue(this.plugin.settings.defaultModelId);
      d.onChange(async (v) => {
        this.plugin.settings.defaultModelId = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(card).setName("\u7CFB\u7EDF\u6307\u4EE4\uFF08\u53EF\u9009\uFF09").setDesc("\u8FFD\u52A0\u7ED9\u6A21\u578B\u7684\u5168\u5C40\u8BBE\u5B9A\uFF0C\u4F8B\u5982\u201C\u7528\u7B80\u6D01\u4E2D\u6587\u56DE\u7B54\u201D").addTextArea((t) => {
      t.setValue(this.plugin.settings.systemInstruction);
      t.onChange(async (v) => {
        this.plugin.settings.systemInstruction = v;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/views/chatView.ts
var import_obsidian2 = require("obsidian");

// src/llm/gemini.ts
var GeminiProvider = class {
  constructor() {
    __publicField(this, "id", "gemini");
  }
  async chat(model, messages, cb, opts) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m;
    const base = model.baseUrl || "https://generativelanguage.googleapis.com/v1beta";
    const url = `${base}/models/${encodeURIComponent(
      model.name
    )}:streamGenerateContent?alt=sse&key=${model.apiKey}`;
    const contents = messages.map((m) => ({
      role: m.role === "model" ? "model" : "user",
      parts: [{ text: m.content }]
    }));
    const body = { contents };
    if ((opts == null ? void 0 : opts.systemInstruction) && opts.systemInstruction.trim()) {
      body.systemInstruction = {
        parts: [{ text: opts.systemInstruction }]
      };
    }
    let res;
    try {
      res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
    } catch (e) {
      (_a = cb.onError) == null ? void 0 : _a.call(cb, new Error("\u7F51\u7EDC\u8BF7\u6C42\u5931\u8D25\uFF1A" + e.message));
      return;
    }
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      (_b = cb.onError) == null ? void 0 : _b.call(cb, new Error(`Gemini API ${res.status}: ${text.slice(0, 300)}`));
      return;
    }
    if (!res.body) {
      (_c = cb.onError) == null ? void 0 : _c.call(cb, new Error("\u54CD\u5E94\u4E3A\u7A7A"));
      return;
    }
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buf = "";
    let usage = null;
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buf += decoder.decode(value, { stream: true });
        const lines = buf.split("\n");
        buf = lines.pop() || "";
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed.startsWith("data:")) continue;
          const json = trimmed.slice(5).trim();
          if (!json || json === "[DONE]") continue;
          try {
            const data = JSON.parse(json);
            const text = ((_g = (_f = (_e = (_d = data.candidates) == null ? void 0 : _d[0]) == null ? void 0 : _e.content) == null ? void 0 : _f.parts) == null ? void 0 : _g.map((p) => p.text || "").join("")) || "";
            if (text) (_h = cb.onToken) == null ? void 0 : _h.call(cb, text);
            if (data.usageMetadata) {
              usage = {
                promptTokens: (_i = data.usageMetadata.promptTokenCount) != null ? _i : 0,
                completionTokens: (_j = data.usageMetadata.candidatesTokenCount) != null ? _j : 0,
                totalTokens: (_k = data.usageMetadata.totalTokenCount) != null ? _k : 0
              };
            }
          } catch (e) {
          }
        }
      }
    } catch (e) {
      (_l = cb.onError) == null ? void 0 : _l.call(cb, new Error("\u8BFB\u53D6\u54CD\u5E94\u5931\u8D25\uFF1A" + e.message));
      return;
    }
    (_m = cb.onDone) == null ? void 0 : _m.call(cb, usage);
  }
};

// src/llm/index.ts
var providers = {
  gemini: new GeminiProvider()
};
function getProvider(id) {
  const p = providers[id];
  if (!p) throw new Error(`\u672A\u77E5\u7684\u4F9B\u5E94\u5546\uFF1A${id}`);
  return p;
}

// src/views/chatView.ts
var VIEW_TYPE_CHAT = "margin-chat";
var ChatView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    __publicField(this, "messages", []);
    __publicField(this, "messagesEl");
    __publicField(this, "inputEl");
    __publicField(this, "modelSelect");
    __publicField(this, "usageEl");
    __publicField(this, "busy", false);
    /** 会话累计用量 */
    __publicField(this, "sessionUsage", { prompt: 0, completion: 0, total: 0 });
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "Margin";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  /** 设置变更后刷新模型下拉 */
  refreshModels() {
    if (!this.modelSelect) return;
    this.populateModels();
  }
  currentModel() {
    var _a;
    const id = (_a = this.modelSelect) == null ? void 0 : _a.value;
    return this.plugin.settings.models.find((m) => m.id === id) || this.plugin.settings.models[0];
  }
  populateModels() {
    this.modelSelect.empty();
    for (const m of this.plugin.settings.models) {
      this.modelSelect.createEl("option", { text: m.name, value: m.id });
    }
    if (this.plugin.settings.defaultModelId) {
      this.modelSelect.value = this.plugin.settings.defaultModelId;
    }
  }
  render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("ai-chat");
    const header = root.createDiv({ cls: "ai-chat-header" });
    this.modelSelect = header.createEl("select", {
      cls: "ai-chat-model-select dropdown"
    });
    this.populateModels();
    const clearBtn = header.createEl("button", {
      cls: "ai-chat-clear",
      text: "\u6E05\u7A7A"
    });
    clearBtn.addEventListener("click", () => {
      this.messages = [];
      this.sessionUsage = { prompt: 0, completion: 0, total: 0 };
      this.renderMessages();
      this.showUsage(null);
    });
    this.messagesEl = root.createDiv({ cls: "ai-chat-messages" });
    this.usageEl = root.createDiv({ cls: "ai-chat-usage" });
    this.showUsage(null);
    const inputWrap = root.createDiv({ cls: "ai-chat-input-wrap" });
    this.inputEl = inputWrap.createEl("textarea", {
      cls: "ai-chat-input",
      placeholder: "\u8F93\u5165\u6D88\u606F\uFF0CEnter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C"
    });
    const sendBtn = inputWrap.createEl("button", {
      cls: "ai-chat-send mod-cta",
      text: "\u53D1\u9001"
    });
    sendBtn.addEventListener("click", () => this.send());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.send();
      }
    });
    this.renderMessages();
  }
  renderMessages() {
    this.messagesEl.empty();
    for (const m of this.messages) {
      const bubble = this.messagesEl.createDiv({
        cls: `ai-msg ai-msg-${m.role}`
      });
      bubble.createEl("div", {
        cls: "ai-msg-role",
        text: m.role === "user" ? "\u4F60" : "AI"
      });
      bubble.createEl("div", { cls: "ai-msg-content", text: m.content });
    }
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  async send() {
    const text = this.inputEl.value.trim();
    if (!text || this.busy) return;
    const model = this.currentModel();
    if (!model) {
      new import_obsidian2.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u6DFB\u52A0 Gemini \u6A21\u578B");
      return;
    }
    this.inputEl.value = "";
    this.messages.push({ role: "user", content: text });
    this.renderMessages();
    this.busy = true;
    const aiBubble = this.messagesEl.createDiv({ cls: "ai-msg ai-msg-model" });
    aiBubble.createEl("div", { cls: "ai-msg-role", text: "AI" });
    const contentEl = aiBubble.createEl("div", {
      cls: "ai-msg-content",
      text: ""
    });
    let acc = "";
    const provider = getProvider(model.provider);
    try {
      await provider.chat(
        model,
        this.messages,
        {
          onToken: (t) => {
            acc += t;
            contentEl.setText(acc);
            this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
          },
          onDone: (usage) => {
            this.messages.push({ role: "model", content: acc });
            if (usage) {
              this.sessionUsage.prompt += usage.promptTokens;
              this.sessionUsage.completion += usage.completionTokens;
              this.sessionUsage.total += usage.totalTokens;
            }
            this.showUsage(usage);
          },
          onError: (e) => {
            new import_obsidian2.Notice("\u9519\u8BEF\uFF1A" + e.message);
            contentEl.setText("\u26A0\uFE0F " + e.message);
          }
        },
        { systemInstruction: this.plugin.settings.systemInstruction }
      );
    } finally {
      this.busy = false;
    }
  }
  showUsage(u) {
    if (!u) {
      this.usageEl.setText(
        `\u4F1A\u8BDD\u7528\u91CF \u2014 \u63D0\u793A ${this.sessionUsage.prompt} \xB7 \u8865\u5168 ${this.sessionUsage.completion} \xB7 \u603B\u8BA1 ${this.sessionUsage.total} tokens`
      );
      return;
    }
    this.usageEl.setText(
      `\u4F1A\u8BDD\u7528\u91CF \u2014 \u63D0\u793A ${this.sessionUsage.prompt} \xB7 \u8865\u5168 ${this.sessionUsage.completion} \xB7 \u603B\u8BA1 ${this.sessionUsage.total} tokens\uFF08\u672C\u6B21 ${u.totalTokens}\uFF09`
    );
  }
};

// src/selection/popover.ts
var import_obsidian3 = require("obsidian");
var Z_TOP = 2147483e3;
var SelectionPopover = class {
  constructor(plugin, editor, selected) {
    __publicField(this, "plugin");
    __publicField(this, "editor");
    __publicField(this, "selected");
    __publicField(this, "messages", []);
    __publicField(this, "from");
    __publicField(this, "to");
    __publicField(this, "root");
    __publicField(this, "messagesEl");
    __publicField(this, "inputEl");
    __publicField(this, "actionsEl");
    __publicField(this, "usageEl");
    __publicField(this, "lastResult", "");
    __publicField(this, "busy", false);
    this.plugin = plugin;
    this.editor = editor;
    this.selected = selected;
    this.from = editor.getCursor("from");
    this.to = editor.getCursor("to");
  }
  open() {
    const root = document.createElement("div");
    root.className = "ai-popover";
    root.style.zIndex = String(Z_TOP);
    root.addEventListener("click", (e) => e.stopPropagation());
    const header = root.createDiv({ cls: "ai-popover-header" });
    const title = header.createSpan({ cls: "ai-popover-title", text: "Margin" });
    title.addClass("ai-popover-drag");
    const close = header.createEl("button", {
      cls: "ai-popover-close",
      text: "\u2715",
      attr: { type: "button", title: "\u5173\u95ED" }
    });
    close.addEventListener("click", (e) => {
      e.stopPropagation();
      this.close();
    });
    const ctx = root.createDiv({ cls: "ai-popover-ctx" });
    ctx.createSpan({ cls: "ai-popover-ctx-label", text: "\u9009\u533A" });
    ctx.createSpan({
      cls: "ai-popover-ctx-text",
      text: this.selected.slice(0, 120) + (this.selected.length > 120 ? "\u2026" : "")
    });
    this.messagesEl = root.createDiv({ cls: "ai-popover-messages" });
    this.usageEl = root.createDiv({ cls: "ai-popover-usage" });
    this.actionsEl = root.createDiv({ cls: "ai-popover-actions" });
    this.renderActions();
    const inputWrap = root.createDiv({ cls: "ai-popover-input-wrap" });
    this.inputEl = inputWrap.createEl("textarea", {
      cls: "ai-popover-input",
      placeholder: "\u57FA\u4E8E\u9009\u533A\u63D0\u95EE\uFF0CEnter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C"
    });
    const send = inputWrap.createEl("button", {
      cls: "ai-popover-send mod-cta",
      text: "\u53D1\u9001"
    });
    send.addEventListener("click", () => this.send());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.send();
      }
    });
    document.body.appendChild(root);
    this.root = root;
    this.inputEl.focus();
    const rect = this.getSelectionRect();
    this.position(rect);
    this.makeDraggable(header);
  }
  /** 读取选区在屏幕上的位置（编辑器内选中文字） */
  getSelectionRect() {
    const sel = window.getSelection();
    if (sel && sel.rangeCount > 0) {
      const r = sel.getRangeAt(0).getBoundingClientRect();
      if (r && (r.width > 0 || r.height > 0)) return r;
    }
    return null;
  }
  /** 固定定位 + 边界钳制 */
  position(rect) {
    if (!this.root) return;
    const w = 380;
    const h = 420;
    let x = rect ? rect.left : window.innerWidth / 2 - w / 2;
    let y = rect ? rect.bottom + 8 : window.innerHeight / 2 - h / 2;
    x = Math.max(8, Math.min(x, window.innerWidth - w - 8));
    y = Math.max(8, Math.min(y, window.innerHeight - h - 8));
    this.root.style.width = w + "px";
    this.root.style.left = x + "px";
    this.root.style.top = y + "px";
  }
  /** 按住头部拖动悬浮窗 */
  makeDraggable(header) {
    let dragging = false;
    let startX = 0;
    let startY = 0;
    let origX = 0;
    let origY = 0;
    header.addEventListener("mousedown", (e) => {
      var _a, _b, _c, _d;
      if (e.target.closest(".ai-popover-close")) return;
      dragging = true;
      startX = e.clientX;
      startY = e.clientY;
      origX = (_b = (_a = this.root) == null ? void 0 : _a.offsetLeft) != null ? _b : 0;
      origY = (_d = (_c = this.root) == null ? void 0 : _c.offsetTop) != null ? _d : 0;
      e.preventDefault();
    });
    document.addEventListener("mousemove", (e) => {
      if (!dragging || !this.root) return;
      let x = origX + (e.clientX - startX);
      let y = origY + (e.clientY - startY);
      x = Math.max(0, Math.min(x, window.innerWidth - this.root.offsetWidth));
      y = Math.max(0, Math.min(y, window.innerHeight - this.root.offsetHeight));
      this.root.style.left = x + "px";
      this.root.style.top = y + "px";
    });
    document.addEventListener("mouseup", () => {
      dragging = false;
    });
  }
  close() {
    var _a;
    (_a = this.root) == null ? void 0 : _a.remove();
    this.root = void 0;
  }
  renderActions() {
    if (!this.actionsEl) return;
    this.actionsEl.empty();
    if (!this.lastResult) {
      this.actionsEl.setText("");
      return;
    }
    const mk = (label, icon, fn) => {
      const b = this.actionsEl.createEl("button", {
        cls: "ai-popover-btn",
        text: `${icon} ${label}`
      });
      b.addEventListener("click", fn);
    };
    mk("\u590D\u5236", "\u{1F4CB}", () => {
      navigator.clipboard.writeText(this.lastResult);
      new import_obsidian3.Notice("\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
    });
    mk("\u63D2\u5165\u5149\u6807", "\u{1F4E5}", () => {
      this.editor.replaceRange(this.lastResult, this.editor.getCursor());
      new import_obsidian3.Notice("\u5DF2\u63D2\u5165\u5230\u5149\u6807\u5904");
    });
    mk("\u8986\u76D6\u9009\u533A", "\u{1F501}", () => {
      this.editor.replaceRange(this.lastResult, this.from, this.to);
      new import_obsidian3.Notice("\u5DF2\u8986\u76D6\u9009\u533A");
    });
    mk("\u7EE7\u7EED\u5BF9\u8BDD", "\u{1F4AC}", () => {
      var _a;
      return (_a = this.inputEl) == null ? void 0 : _a.focus();
    });
  }
  /** 渲染完整对话历史（用户 + AI），用于刷新显示 */
  renderMessages() {
    if (!this.messagesEl) return;
    this.messagesEl.empty();
    for (const m of this.messages) {
      const bubble = this.messagesEl.createDiv({
        cls: `ai-popover-msg ai-popover-msg-${m.role}`
      });
      bubble.createDiv({
        cls: "ai-popover-msg-role",
        text: m.role === "user" ? "\u4F60" : "AI"
      });
      bubble.createDiv({
        cls: "ai-popover-msg-content",
        text: this.displayText(m)
      });
    }
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  /** 首条用户消息带选区上下文，展示时只显示问题本身 */
  displayText(m) {
    const marker = "\u8BF7\u57FA\u4E8E\u4E0A\u8FF0\u6587\u672C\u56DE\u7B54\u6211\u7684\u95EE\u9898\uFF1A";
    const i = m.content.indexOf(marker);
    if (m.role === "user" && i >= 0) {
      return "\u{1F4CC} \u57FA\u4E8E\u9009\u533A\uFF1A" + m.content.slice(i + marker.length);
    }
    return m.content;
  }
  async send() {
    var _a;
    const text = (_a = this.inputEl) == null ? void 0 : _a.value.trim();
    if (!text || this.busy) return;
    const model = this.plugin.settings.models.find(
      (m) => m.id === this.plugin.settings.defaultModelId
    ) || this.plugin.settings.models[0];
    if (!model) {
      new import_obsidian3.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u6DFB\u52A0 Gemini \u6A21\u578B");
      return;
    }
    if (this.messages.length === 0) {
      this.messages.push({
        role: "user",
        content: `\u4EE5\u4E0B\u662F\u9009\u4E2D\u7684\u6587\u672C\uFF1A
"""
${this.selected}
"""

\u8BF7\u57FA\u4E8E\u4E0A\u8FF0\u6587\u672C\u56DE\u7B54\u6211\u7684\u95EE\u9898\uFF1A${text}`
      });
    } else {
      this.messages.push({ role: "user", content: text });
    }
    if (this.inputEl) this.inputEl.value = "";
    this.busy = true;
    this.renderMessages();
    const aiBubble = this.messagesEl.createDiv({
      cls: "ai-popover-msg ai-popover-msg-model"
    });
    aiBubble.createDiv({ cls: "ai-popover-msg-role", text: "AI" });
    const contentEl = aiBubble.createDiv({
      cls: "ai-popover-msg-content",
      text: ""
    });
    let acc = "";
    const provider = getProvider(model.provider);
    try {
      await provider.chat(
        model,
        this.messages,
        {
          onToken: (t) => {
            acc += t;
            contentEl.setText(acc);
            this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
          },
          onDone: (u) => {
            this.messages.push({ role: "model", content: acc });
            this.lastResult = acc;
            this.renderActions();
            this.renderUsage(u);
          },
          onError: (e) => {
            new import_obsidian3.Notice("\u9519\u8BEF\uFF1A" + e.message);
            contentEl.setText("\u26A0\uFE0F " + e.message);
          }
        },
        { systemInstruction: this.plugin.settings.systemInstruction }
      );
    } finally {
      this.busy = false;
    }
  }
  renderUsage(u) {
    if (!this.usageEl) return;
    if (!u) {
      this.usageEl.setText("");
      return;
    }
    this.usageEl.setText(
      `\u7528\u91CF \u2014 \u63D0\u793A ${u.promptTokens} \xB7 \u8865\u5168 ${u.completionTokens} \xB7 \u603B\u8BA1 ${u.totalTokens} tokens`
    );
  }
};

// src/main.ts
var AIPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_CHAT, (leaf) => new ChatView(leaf, this));
    this.addRibbonIcon("message-square", "\u6253\u5F00 AI Chat", () => {
      this.activateChat();
    });
    this.addCommand({
      id: "open-ai-chat",
      name: "\u6253\u5F00 AI Chat",
      callback: () => this.activateChat()
    });
    this.registerEvent(
      this.app.workspace.on(
        "editor-menu",
        (menu, editor) => {
          const selected = editor.getSelection();
          if (!selected) return;
          menu.addItem((item) => {
            item.setTitle("Margin").setIcon("sparkles").onClick(() => {
              const popover = new SelectionPopover(
                this,
                editor,
                selected
              );
              popover.open();
            });
          });
        }
      )
    );
    this.addSettingTab(new AISettingsTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("margin:settings-changed", () => {
        const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
        if (leaf) leaf.view.refreshModels();
      })
    );
  }
  onunload() {
  }
  async activateChat() {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
    }
    this.app.workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.app.workspace.trigger("margin:settings-changed");
  }
};
