/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/settings.ts
var import_obsidian3 = require("obsidian");

// src/llm/gemini.ts
var import_obsidian2 = require("obsidian");

// src/i18n.ts
var import_obsidian = require("obsidian");
var zh = {
  // common
  "common.send": "\u53D1\u9001",
  "common.you": "\u4F60",
  "common.copy": "\u590D\u5236\u672C\u6761\u6D88\u606F",
  "common.edit_resend": "\u7F16\u8F91\u5E76\u91CD\u53D1",
  "common.remove_attach": "\u79FB\u9664\u5173\u8054",
  "common.retry": "\u91CD\u65B0\u83B7\u53D6\u8FD9\u4E00\u8F6E\u56DE\u7B54",
  "common.close": "\u5173\u95ED",
  "common.no_model": "\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u6DFB\u52A0\u6A21\u578B",
  "common.no_model_selected": "\u672A\u9009\u6A21\u578B",
  "common.error": "\u9519\u8BEF\uFF1A",
  "common.copied": "\u5DF2\u590D\u5236",
  "common.copy_failed": "\u590D\u5236\u5931\u8D25",
  "gemini.location_blocked": "\u5F53\u524D\u7F51\u7EDC\u51FA\u53E3\u5730\u533A\u4E0D\u88AB Gemini \u652F\u6301\uFF08\u5982\u9999\u6E2F\uFF09\u3002\u8BF7\u5C06\u4EE3\u7406\u8282\u70B9\u5207\u6362\u5230\u7F8E\u56FD\u3001\u65E5\u672C\u3001\u65B0\u52A0\u5761\u3001\u53F0\u6E7E\u7B49\u652F\u6301\u5730\u533A\u540E\u91CD\u8BD5\u3002",
  // commands
  "cmd.open_chat": "\u6253\u5F00 AI Chat",
  "cmd.open_popover": "\u6253\u5F00 Margin \u60AC\u6D6E\u5BF9\u8BDD",
  // chat
  "chat.new": "\u65B0\u5BF9\u8BDD",
  "chat.placeholder": "\u8F93\u5165\u6D88\u606F\uFF0CEnter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C",
  "chat.note_not_found": "\u672A\u627E\u5230\u7B14\u8BB0\uFF1A{name}",
  "chat.this_usage": "\u672C\u6B21 {prompt}+{completion}={total}",
  "chat.session_usage": "\u4F1A\u8BDD\u7D2F\u8BA1 {prompt}+{completion}={total} tokens \xB7 {tail}",
  "chat.attached_notes": "\u5173\u8054\u7B14\u8BB0",
  // popover
  "popover.no_note": "\u5F53\u524D\u6CA1\u6709\u6253\u5F00\u7684\u7B14\u8BB0",
  "popover.selection": "\u9009\u533A",
  "popover.placeholder_sel": "\u57FA\u4E8E\u9009\u533A\u63D0\u95EE\uFF0CEnter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C",
  "popover.placeholder": "\u8F93\u5165\u95EE\u9898\uFF0CEnter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C",
  "popover.insert": "\u63D2\u5165\u5149\u6807",
  "popover.overwrite": "\u8986\u76D6\u9009\u533A",
  "popover.inserted": "\u5DF2\u63D2\u5165\u5230\u5149\u6807\u5904",
  "popover.overwritten": "\u5DF2\u8986\u76D6\u9009\u533A",
  "popover.ask_marker": "\u8BF7\u57FA\u4E8E\u4E0A\u8FF0\u6587\u672C\u56DE\u7B54\u6211\u7684\u95EE\u9898\uFF1A",
  "popover.selection_label": "\u57FA\u4E8E\u9009\u533A\uFF1A",
  "popover.ask_prompt": '\u4EE5\u4E0B\u662F\u9009\u4E2D\u7684\u6587\u672C\uFF1A\n"""\n{selection}\n"""\n\n\u8BF7\u57FA\u4E8E\u4E0A\u8FF0\u6587\u672C\u56DE\u7B54\u6211\u7684\u95EE\u9898\uFF1A{question}',
  "popover.this_usage": "\u672C\u6B21 \u63D0\u793A {prompt} \xB7 \u8865\u5168 {completion} \xB7 \u603B\u8BA1 {total}",
  // settings
  "settings.title": "Margin \u8BBE\u7F6E",
  "settings.eye": "\u663E\u793A / \u9690\u85CF",
  "settings.api_key": "API Key",
  "settings.add_model": "\u6DFB\u52A0\u6A21\u578B",
  "settings.add_hint": "\u6A21\u578B\u540D\u79F0\u586B\u4F60\u60F3\u8981\u7684\u578B\u53F7\uFF08\u5982 gemini-3.5-flash\uFF09\uFF0CAPI Key \u4ECE Google AI Studio \u83B7\u53D6\u3002\u53EF\u6DFB\u52A0\u591A\u4E2A\u5E76\u968F\u65F6\u5207\u6362\u3002",
  "settings.model_name_placeholder": "\u6A21\u578B\u540D\u79F0\uFF0C\u5982 gemini-3.5-flash",
  "settings.need_name_key": "\u8BF7\u586B\u5199\u6A21\u578B\u540D\u79F0\u548C API Key",
  "settings.models": "\u5DF2\u6DFB\u52A0\u6A21\u578B",
  "settings.empty": "\u8FD8\u6CA1\u6709\u6A21\u578B\uFF0C\u5148\u5728\u4E0A\u65B9\u6DFB\u52A0\u3002",
  "settings.untested": "\u672A\u6D4B\u8BD5",
  "settings.set_default": "\u8BBE\u4E3A\u9ED8\u8BA4",
  "settings.is_default": "\u9ED8\u8BA4 \u2713",
  "settings.test": "\u6D4B\u8BD5",
  "settings.testing": "\u6D4B\u8BD5\u4E2D\u2026",
  "settings.test_ok": "\u2713 {name} \u8FDE\u63A5\u6210\u529F \xB7 {limits}",
  "settings.no_limits": "\u65E0\u9650\u989D\u4FE1\u606F",
  "settings.test_fail_prefix": "\u2717 \u6D4B\u8BD5\u5931\u8D25\uFF1A",
  "settings.unknown_error": "\u672A\u77E5\u9519\u8BEF",
  "settings.edit": "\u4FEE\u6539",
  "settings.delete": "\u5220\u9664",
  "settings.model_name": "\u6A21\u578B\u540D\u79F0",
  "settings.base_url_placeholder": "base URL\uFF08\u53EF\u9009\uFF0C\u4EE3\u7406 / \u7F51\u5173\u7528\uFF09",
  "settings.save": "\u4FDD\u5B58",
  "settings.cancel": "\u53D6\u6D88",
  "settings.system_instruction": "\u7CFB\u7EDF\u6307\u4EE4\uFF08\u53EF\u9009\uFF09",
  "settings.system_instruction_desc": "\u8FFD\u52A0\u7ED9\u6A21\u578B\u7684\u5168\u5C40\u8BBE\u5B9A\uFF0C\u4F8B\u5982\u201C\u7528\u7B80\u6D01\u4E2D\u6587\u56DE\u7B54\u201D",
  "settings.limit_context": "\u4E0A\u4E0B\u6587 {n}",
  "settings.limit_output": "\u8F93\u51FA {n}"
};
var en = {
  "common.send": "Send",
  "common.you": "You",
  "common.copy": "Copy message",
  "common.edit_resend": "Edit & resend",
  "common.remove_attach": "Remove",
  "common.retry": "Retry this turn",
  "common.close": "Close",
  "common.no_model": "Please add a model in settings first",
  "common.no_model_selected": "No model",
  "common.error": "Error: ",
  "common.copied": "Copied",
  "common.copy_failed": "Copy failed",
  "gemini.location_blocked": "Your current network region is not supported by Gemini (e.g. Hong Kong). Switch your proxy node to a supported region (US/JP/SG/TW) and retry.",
  "cmd.open_chat": "Open AI Chat",
  "cmd.open_popover": "Open Margin Popover",
  "chat.new": "New chat",
  "chat.placeholder": "Type a message, Enter to send, Shift+Enter for newline",
  "chat.note_not_found": "Note not found: {name}",
  "chat.this_usage": "This: {prompt}+{completion}={total}",
  "chat.session_usage": "Session {prompt}+{completion}={total} tokens \xB7 {tail}",
  "chat.attached_notes": "Attached notes",
  "popover.no_note": "No note is open",
  "popover.selection": "Selection",
  "popover.placeholder_sel": "Ask about the selection, Enter to send",
  "popover.placeholder": "Type a question, Enter to send",
  "popover.insert": "Insert at cursor",
  "popover.overwrite": "Overwrite selection",
  "popover.inserted": "Inserted at cursor",
  "popover.overwritten": "Selection overwritten",
  "popover.ask_marker": "Please answer my question based on the text above:",
  "popover.selection_label": "Based on selection: ",
  "popover.ask_prompt": 'Here is the selected text:\n"""\n{selection}\n"""\n\nPlease answer my question based on the text above: {question}',
  "popover.this_usage": "This: prompt {prompt} \xB7 completion {completion} \xB7 total {total}",
  "settings.title": "Margin Settings",
  "settings.eye": "Show / Hide",
  "settings.api_key": "API Key",
  "settings.add_model": "Add model",
  "settings.add_hint": "Enter the model name (e.g. gemini-3.5-flash) and an API key from Google AI Studio. You can add multiple models and switch anytime.",
  "settings.model_name_placeholder": "Model name, e.g. gemini-3.5-flash",
  "settings.need_name_key": "Please fill in model name and API key",
  "settings.models": "Added models",
  "settings.empty": "No models yet. Add one above.",
  "settings.untested": "Not tested",
  "settings.set_default": "Set default",
  "settings.is_default": "Default \u2713",
  "settings.test": "Test",
  "settings.testing": "Testing\u2026",
  "settings.test_ok": "\u2713 {name} connected \xB7 {limits}",
  "settings.no_limits": "No limit info",
  "settings.test_fail_prefix": "\u2717 Test failed: ",
  "settings.unknown_error": "Unknown error",
  "settings.edit": "Edit",
  "settings.delete": "Delete",
  "settings.model_name": "Model name",
  "settings.base_url_placeholder": "base URL (optional, for proxy/gateway)",
  "settings.save": "Save",
  "settings.cancel": "Cancel",
  "settings.system_instruction": "System instruction (optional)",
  "settings.system_instruction_desc": 'Global instructions appended to the model, e.g. "answer in concise Chinese"',
  "settings.limit_context": "Context {n}",
  "settings.limit_output": "Output {n}"
};
var lang = "zh";
function detectObsidianLang() {
  try {
    if ((0, import_obsidian.getLanguage)().startsWith("zh")) return "zh";
  } catch (e) {
  }
  return "en";
}
function setLang(l) {
  lang = l;
}
function t(key) {
  var _a;
  return (_a = lang === "zh" ? zh[key] : en[key]) != null ? _a : key;
}
function tf(key, params) {
  let s = t(key);
  for (const [k, v] of Object.entries(params)) {
    s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
  }
  return s;
}

// src/llm/gemini.ts
function friendlyError(status, body) {
  if (body.includes("User location is not supported")) {
    return t("gemini.location_blocked");
  }
  return `Gemini API ${status}: ${body.slice(0, 300)}`;
}
async function testGeminiModel(model) {
  const base = model.baseUrl || "https://generativelanguage.googleapis.com/v1beta";
  const url = `${base}/models/${encodeURIComponent(
    model.name
  )}?key=${model.apiKey}`;
  try {
    const r = await (0, import_obsidian2.requestUrl)({ url, throw: false });
    if (r.status >= 400) {
      const b = r.text || "";
      return { ok: false, error: friendlyError(r.status, b) };
    }
    const j = r.json;
    const meta = {};
    if (typeof j.inputTokenLimit === "number") {
      meta.inputTokenLimit = j.inputTokenLimit;
    }
    if (typeof j.outputTokenLimit === "number") {
      meta.outputTokenLimit = j.outputTokenLimit;
    }
    return { ok: true, meta };
  } catch (e) {
    return { ok: false, error: (e == null ? void 0 : e.message) || String(e) };
  }
}
var GeminiProvider = class {
  constructor() {
    __publicField(this, "id", "gemini");
  }
  getModelMeta(model) {
    return testGeminiModel(model);
  }
  async chat(model, messages, cb, opts) {
    var _a, _b, _c, _d;
    const base = model.baseUrl || "https://generativelanguage.googleapis.com/v1beta";
    const url = `${base}/models/${encodeURIComponent(
      model.name
    )}:streamGenerateContent?alt=sse&key=${model.apiKey}`;
    const contents = messages.map((m) => ({
      role: m.role === "model" ? "model" : "user",
      parts: [{ text: m.content }]
    }));
    const body = { contents };
    if ((opts == null ? void 0 : opts.systemInstruction) && opts.systemInstruction.trim()) {
      body.systemInstruction = {
        parts: [{ text: opts.systemInstruction }]
      };
    }
    let usage = null;
    let emitted = false;
    const handleDataJson = (json) => {
      var _a2, _b2, _c2, _d2, _e, _f, _g, _h;
      try {
        const data = JSON.parse(json);
        const piece = ((_d2 = (_c2 = (_b2 = (_a2 = data.candidates) == null ? void 0 : _a2[0]) == null ? void 0 : _b2.content) == null ? void 0 : _c2.parts) == null ? void 0 : _d2.map((p) => p.text || "").join("")) || "";
        if (piece) {
          emitted = true;
          (_e = cb.onToken) == null ? void 0 : _e.call(cb, piece);
        }
        if (data.usageMetadata) {
          usage = {
            promptTokens: (_f = data.usageMetadata.promptTokenCount) != null ? _f : 0,
            completionTokens: (_g = data.usageMetadata.candidatesTokenCount) != null ? _g : 0,
            totalTokens: (_h = data.usageMetadata.totalTokenCount) != null ? _h : 0
          };
        }
      } catch (e) {
      }
    };
    const feedSSELines = (lines) => {
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed.startsWith("data:")) continue;
        const json = trimmed.slice(5).trim();
        if (!json || json === "[DONE]") continue;
        handleDataJson(json);
      }
    };
    const xhrResult = await new Promise((resolve) => {
      const xhr = new XMLHttpRequest();
      xhr.open("POST", url);
      xhr.setRequestHeader("Content-Type", "application/json");
      let buf = "";
      let lastLen = 0;
      const drain = () => {
        buf += xhr.responseText.slice(lastLen);
        lastLen = xhr.responseText.length;
        const lines = buf.split("\n");
        buf = lines.pop() || "";
        feedSSELines(lines);
      };
      xhr.onprogress = drain;
      xhr.onload = () => {
        var _a2;
        drain();
        if (xhr.status < 400) {
          (_a2 = cb.onDone) == null ? void 0 : _a2.call(cb, usage);
          resolve({ ok: true });
        } else {
          resolve({
            ok: false,
            error: friendlyError(xhr.status, xhr.responseText || "")
          });
        }
      };
      xhr.onerror = () => resolve({ ok: false, error: "\u7F51\u7EDC\u8BF7\u6C42\u5931\u8D25" });
      xhr.onabort = () => resolve({ ok: false, error: "\u8BF7\u6C42\u5DF2\u4E2D\u65AD" });
      try {
        xhr.send(JSON.stringify(body));
      } catch (e) {
        resolve({ ok: false, error: "\u7F51\u7EDC\u8BF7\u6C42\u5931\u8D25\uFF1A" + e.message });
      }
    });
    if (xhrResult.ok) return;
    if (emitted) {
      (_a = cb.onError) == null ? void 0 : _a.call(cb, new Error(xhrResult.error || "\u8BF7\u6C42\u5931\u8D25"));
      return;
    }
    try {
      const r = await (0, import_obsidian2.requestUrl)({
        url,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
        throw: false
      });
      if (r.status >= 400) {
        (_b = cb.onError) == null ? void 0 : _b.call(cb, new Error(friendlyError(r.status, r.text || "")));
        return;
      }
      usage = null;
      feedSSELines((r.text || "").split("\n"));
      (_c = cb.onDone) == null ? void 0 : _c.call(cb, usage);
    } catch (e) {
      (_d = cb.onError) == null ? void 0 : _d.call(cb, new Error("\u7F51\u7EDC\u8BF7\u6C42\u5931\u8D25\uFF1A" + e.message));
    }
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  models: [],
  defaultModelId: "",
  systemInstruction: ""
};
function fmtLimit(n) {
  if (n == null) return "\u2014";
  if (n >= 1e6) return (n / 1e6).toFixed(n % 1e6 === 0 ? 0 : 1) + "M";
  if (n >= 1e3) return Math.round(n / 1e3) + "K";
  return String(n);
}
function modelLimitsText(m) {
  const inL = m.inputTokenLimit != null ? tf("settings.limit_context", { n: fmtLimit(m.inputTokenLimit) }) : null;
  const outL = m.outputTokenLimit != null ? tf("settings.limit_output", { n: fmtLimit(m.outputTokenLimit) }) : null;
  const parts = [inL, outL].filter(Boolean);
  return parts.join(" \xB7 ");
}
function createKeyInput(container, value = "") {
  const wrap = container.createDiv({ cls: "ai-set-key-wrap" });
  const input = wrap.createEl("input", {
    cls: "ai-set-input ai-set-key-input",
    placeholder: t("settings.api_key"),
    type: "password",
    value
  });
  const eye = wrap.createEl("button", {
    cls: "ai-set-eye",
    text: "\u{1F441}",
    attr: { type: "button", title: t("settings.eye") }
  });
  eye.addEventListener("click", () => {
    const show = input.type === "password";
    input.type = show ? "text" : "password";
    eye.setText(show ? "\u{1F648}" : "\u{1F441}");
  });
  return input;
}
var AISettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("ai-set");
    new import_obsidian3.Setting(containerEl).setName(t("settings.title")).setHeading();
    this.renderAddModel(containerEl);
    this.renderModelList(containerEl);
    this.renderGeneral(containerEl);
  }
  /** 添加模型 */
  renderAddModel(containerEl) {
    const card = containerEl.createDiv({ cls: "ai-set-card" });
    new import_obsidian3.Setting(card).setName(t("settings.add_model")).setHeading();
    card.createEl("p", {
      cls: "ai-set-hint",
      text: t("settings.add_hint")
    });
    const addWrap = card.createDiv({ cls: "ai-set-add" });
    const nameInput = addWrap.createEl("input", {
      cls: "ai-set-input",
      placeholder: t("settings.model_name_placeholder")
    });
    const keyInput = createKeyInput(addWrap);
    const addBtn = addWrap.createEl("button", {
      cls: "ai-set-add-btn mod-cta",
      text: t("settings.add_model")
    });
    addBtn.addEventListener("click", () => {
      const name = nameInput.value.trim();
      const key = keyInput.value.trim();
      if (!name || !key) {
        new import_obsidian3.Notice(t("settings.need_name_key"));
        return;
      }
      void this.addModel(name, key);
    });
  }
  /** 添加模型（提取自 addBtn handler，避免 async 箭头被 lint 标记） */
  async addModel(name, key) {
    const model = {
      id: "m_" + Date.now().toString(36) + Math.random().toString(36).slice(2, 6),
      name,
      provider: "gemini",
      apiKey: key
    };
    this.plugin.settings.models.push(model);
    if (!this.plugin.settings.defaultModelId) {
      this.plugin.settings.defaultModelId = model.id;
    }
    await this.plugin.saveSettings();
    this.display();
  }
  /** 模型列表 */
  renderModelList(containerEl) {
    const card = containerEl.createDiv({ cls: "ai-set-card" });
    new import_obsidian3.Setting(card).setName(t("settings.models")).setHeading();
    if (this.plugin.settings.models.length === 0) {
      card.createEl("p", {
        cls: "ai-set-empty",
        text: t("settings.empty")
      });
      return;
    }
    this.plugin.settings.models.forEach((m) => {
      const row = card.createDiv({ cls: "ai-set-model-row" });
      const info = row.createDiv({ cls: "ai-set-model-info" });
      info.createSpan({ cls: "ai-set-model-name", text: m.name });
      info.createSpan({ cls: "ai-set-model-provider", text: m.provider });
      const limitsSpan = info.createSpan({
        cls: "ai-set-model-limits",
        text: modelLimitsText(m)
      });
      if (!limitsSpan.getText()) limitsSpan.setText(t("settings.untested"));
      const actions = row.createDiv({ cls: "ai-set-model-actions" });
      const isDefault = this.plugin.settings.defaultModelId === m.id;
      const def = actions.createEl("button", {
        cls: "ai-set-model-btn" + (isDefault ? " is-default" : ""),
        text: isDefault ? t("settings.is_default") : t("settings.set_default")
      });
      def.addEventListener("click", () => {
        void this.setDefaultModel(m.id);
      });
      const testBtn = actions.createEl("button", {
        cls: "ai-set-model-btn",
        text: t("settings.test")
      });
      testBtn.addEventListener("click", () => {
        void this.testModel(m, testBtn);
      });
      const edit = actions.createEl("button", {
        cls: "ai-set-model-btn",
        text: t("settings.edit")
      });
      edit.addEventListener("click", () => this.renderEditForm(row, m));
      const del = actions.createEl("button", {
        cls: "ai-set-model-btn ai-set-model-del",
        text: t("settings.delete")
      });
      del.addEventListener("click", () => {
        void this.deleteModel(m);
      });
    });
  }
  /** 设为默认（提取自 def 按钮 handler） */
  async setDefaultModel(id) {
    this.plugin.settings.defaultModelId = id;
    await this.plugin.saveSettings();
    this.display();
  }
  /** 测试连接并回填限额（提取自 testBtn handler） */
  async testModel(m, testBtn) {
    testBtn.setText(t("settings.testing"));
    const r = await testGeminiModel(m);
    if (r.ok && r.meta) {
      m.inputTokenLimit = r.meta.inputTokenLimit;
      m.outputTokenLimit = r.meta.outputTokenLimit;
      await this.plugin.saveSettings();
      new import_obsidian3.Notice(
        tf("settings.test_ok", {
          name: m.name,
          limits: modelLimitsText(m) || t("settings.no_limits")
        })
      );
      this.display();
    } else {
      new import_obsidian3.Notice(
        t("settings.test_fail_prefix") + (r.error || t("settings.unknown_error"))
      );
      testBtn.setText(t("settings.test"));
    }
  }
  /** 删除模型（提取自 del 按钮 handler） */
  async deleteModel(m) {
    var _a, _b;
    this.plugin.settings.models = this.plugin.settings.models.filter(
      (x) => x.id !== m.id
    );
    if (this.plugin.settings.defaultModelId === m.id) {
      this.plugin.settings.defaultModelId = (_b = (_a = this.plugin.settings.models[0]) == null ? void 0 : _a.id) != null ? _b : "";
    }
    await this.plugin.saveSettings();
    this.display();
  }
  /** 行内编辑 */
  renderEditForm(row, m) {
    var _a;
    row.empty();
    row.addClass("is-editing");
    const nameInput = row.createEl("input", {
      cls: "ai-set-input",
      value: m.name,
      placeholder: t("settings.model_name")
    });
    const keyInput = createKeyInput(row, m.apiKey);
    const urlInput = row.createEl("input", {
      cls: "ai-set-input",
      value: (_a = m.baseUrl) != null ? _a : "",
      placeholder: t("settings.base_url_placeholder")
    });
    const btnWrap = row.createDiv({ cls: "ai-set-model-actions" });
    const save = btnWrap.createEl("button", {
      cls: "ai-set-model-btn mod-cta",
      text: t("settings.save")
    });
    save.addEventListener("click", () => {
      m.name = nameInput.value.trim() || m.name;
      m.apiKey = keyInput.value.trim() || m.apiKey;
      m.baseUrl = urlInput.value.trim() || void 0;
      void this.plugin.saveSettings().then(() => this.display());
    });
    const cancel = btnWrap.createEl("button", {
      cls: "ai-set-model-btn",
      text: t("settings.cancel")
    });
    cancel.addEventListener("click", () => this.display());
  }
  /** 系统指令 */
  renderGeneral(containerEl) {
    const card = containerEl.createDiv({ cls: "ai-set-card" });
    new import_obsidian3.Setting(card).setName(t("settings.system_instruction")).setDesc(t("settings.system_instruction_desc")).addTextArea((ta) => {
      ta.setValue(this.plugin.settings.systemInstruction);
      ta.onChange((v) => {
        this.plugin.settings.systemInstruction = v;
        void this.plugin.saveSettings();
      });
    });
  }
};

// src/views/chatView.ts
var import_obsidian6 = require("obsidian");

// src/llm/index.ts
var providers = {
  gemini: new GeminiProvider()
};
function getProvider(id) {
  const p = providers[id];
  if (!p) throw new Error(`\u672A\u77E5\u7684\u4F9B\u5E94\u5546\uFF1A${id}`);
  return p;
}

// src/util.ts
var import_obsidian4 = require("obsidian");
function electronClipboard() {
  var _a;
  try {
    const electron = require("electron");
    return (_a = electron == null ? void 0 : electron.clipboard) != null ? _a : null;
  } catch (e) {
    return null;
  }
}
async function copyViaNavigator(text) {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch (e) {
  }
  return false;
}
function copyViaExecCommand(text) {
  try {
    const ta = document.body.createEl("textarea", {
      cls: "ai-copy-helper"
    });
    ta.value = text;
    ta.focus();
    ta.select();
    const ok = document.execCommand("copy");
    ta.remove();
    return ok;
  } catch (e) {
    return false;
  }
}
async function copyText(text) {
  if (import_obsidian4.Platform.isDesktop) {
    const cb = electronClipboard();
    if (cb) {
      try {
        cb.writeText(text);
        if (cb.readText() === text) {
          new import_obsidian4.Notice(t("common.copied"));
          return;
        }
      } catch (e) {
      }
    }
    if (copyViaExecCommand(text)) {
      new import_obsidian4.Notice(t("common.copied"));
      return;
    }
    new import_obsidian4.Notice(t("common.copy_failed"));
    return;
  }
  if (await copyViaNavigator(text)) {
    new import_obsidian4.Notice(t("common.copied"));
    return;
  }
  if (copyViaExecCommand(text)) {
    new import_obsidian4.Notice(t("common.copied"));
    return;
  }
  new import_obsidian4.Notice(t("common.copy_failed"));
}

// src/linkSuggest.ts
var import_obsidian5 = require("obsidian");
var NoteLinkSuggest = class {
  constructor(app, input, onPick) {
    __publicField(this, "app");
    __publicField(this, "input");
    __publicField(this, "onPick");
    __publicField(this, "el", null);
    __publicField(this, "items", []);
    __publicField(this, "selected", 0);
    __publicField(this, "match", null);
    this.app = app;
    this.input = input;
    this.onPick = onPick;
    this.input.addEventListener("input", () => this.refresh());
    this.input.addEventListener("keydown", (e) => this.onKeydown(e));
    this.input.addEventListener("scroll", () => this.close());
    document.addEventListener("mousedown", (e) => {
      if (this.el && !this.el.contains(e.target)) this.close();
    });
  }
  /** 找到光标前未闭合的 [[ 前缀 */
  findMatch() {
    var _a;
    const pos = (_a = this.input.selectionStart) != null ? _a : this.input.value.length;
    const text = this.input.value.slice(0, pos);
    const start = text.lastIndexOf("[[");
    if (start < 0) return null;
    const after = text.slice(start + 2);
    if (after.includes("]]")) return null;
    if (after.includes("\n")) return null;
    return { start, end: pos, query: after };
  }
  refresh() {
    const m = this.findMatch();
    if (!m) {
      this.close();
      return;
    }
    const q = m.query.toLowerCase();
    const files = this.app.vault.getMarkdownFiles().filter((f) => !q || f.basename.toLowerCase().includes(q)).sort((a, b) => {
      const aStarts = a.basename.toLowerCase().startsWith(q) ? 0 : 1;
      const bStarts = b.basename.toLowerCase().startsWith(q) ? 0 : 1;
      return aStarts - bStarts || a.basename.localeCompare(b.basename);
    }).slice(0, 8);
    if (files.length === 0) {
      this.close();
      return;
    }
    this.match = { start: m.start, end: m.end };
    this.items = files;
    this.selected = 0;
    this.render();
  }
  render() {
    var _a, _b;
    if (!this.el) {
      this.el = document.body.createDiv({ cls: "ai-link-suggest" });
    }
    this.el.empty();
    for (let i = 0; i < this.items.length; i++) {
      const f = this.items[i];
      const item = this.el.createDiv({
        cls: "ai-link-suggest-item" + (i === this.selected ? " is-selected" : ""),
        attr: { "data-path": f.path }
      });
      const icon = item.createSpan({ cls: "ai-link-suggest-item-icon" });
      (0, import_obsidian5.setIcon)(icon, "file-text");
      item.createSpan({ cls: "ai-link-suggest-item-name", text: f.basename });
      const parent = (_b = (_a = f.parent) == null ? void 0 : _a.path) != null ? _b : "";
      item.createSpan({ cls: "ai-link-suggest-item-path", text: parent });
      item.addEventListener("mousedown", (e) => {
        e.preventDefault();
        this.selected = i;
        this.pick();
      });
    }
    const rect = this.input.getBoundingClientRect();
    this.el.style.left = rect.left + "px";
    this.el.style.width = Math.min(340, rect.width) + "px";
    const spaceAbove = rect.top - 8;
    const h = this.el.offsetHeight;
    this.el.style.top = spaceAbove > h + 8 ? rect.top - h - 4 + "px" : rect.bottom + 4 + "px";
  }
  onKeydown(e) {
    if (!this.el) return;
    if (e.key === "ArrowDown") {
      e.preventDefault();
      this.selected = (this.selected + 1) % this.items.length;
      this.highlight();
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      this.selected = (this.selected - 1 + this.items.length) % this.items.length;
      this.highlight();
    } else if (e.key === "Enter" || e.key === "Tab") {
      e.preventDefault();
      this.pick();
    } else if (e.key === "Escape") {
      e.preventDefault();
      this.close();
    }
  }
  highlight() {
    if (!this.el) return;
    for (let i = 0; i < this.el.children.length; i++) {
      this.el.children[i].toggleClass("is-selected", i === this.selected);
    }
  }
  pick() {
    const file = this.items[this.selected];
    const m = this.match;
    this.close();
    if (file && m) this.onPick(file, m);
  }
  close() {
    var _a;
    (_a = this.el) == null ? void 0 : _a.remove();
    this.el = null;
    this.match = null;
    this.items = [];
  }
};

// src/views/chatView.ts
var VIEW_TYPE_CHAT = "margin-chat";
var ChatView = class extends import_obsidian6.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    __publicField(this, "messages", []);
    __publicField(this, "histories", /* @__PURE__ */ new Map());
    __publicField(this, "usageByNote", /* @__PURE__ */ new Map());
    __publicField(this, "noteKey", "");
    __publicField(this, "fileOpenRef", null);
    __publicField(this, "messagesEl");
    __publicField(this, "inputEl");
    __publicField(this, "modelSelect");
    __publicField(this, "usageEl");
    __publicField(this, "attachEl");
    __publicField(this, "attachedNotes", []);
    __publicField(this, "linkSuggest");
    __publicField(this, "busy", false);
    __publicField(this, "sessionUsage", { prompt: 0, completion: 0, total: 0 });
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "Margin";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    this.render();
    this.noteKey = this.currentNote();
    this.loadNote();
    this.autoAttachCurrentNote();
    this.fileOpenRef = this.app.workspace.on(
      "file-open",
      () => this.switchNote()
    );
  }
  async onClose() {
    if (this.fileOpenRef) this.app.workspace.offref(this.fileOpenRef);
    this.saveNote();
  }
  currentNote() {
    var _a, _b;
    return (_b = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) != null ? _b : "(\u65E0\u7B14\u8BB0)";
  }
  saveNote() {
    if (!this.noteKey) return;
    this.histories.set(this.noteKey, this.messages);
    this.usageByNote.set(this.noteKey, { ...this.sessionUsage });
  }
  loadNote() {
    var _a, _b;
    this.messages = (_a = this.histories.get(this.noteKey)) != null ? _a : [];
    this.sessionUsage = (_b = this.usageByNote.get(this.noteKey)) != null ? _b : { prompt: 0, completion: 0, total: 0 };
    this.renderMessages();
    this.showUsage(null);
  }
  /** 渲染输入框内的关联笔记 chip（可删除） */
  renderAttachedChips() {
    if (!this.attachEl) return;
    this.attachEl.empty();
    if (this.attachedNotes.length === 0) return;
    for (const n of this.attachedNotes) {
      const chip = this.attachEl.createSpan({ cls: "ai-chat-attach-chip" });
      chip.createSpan({ text: "[[" + n.basename + "]]" });
      const rm = chip.createEl("button", {
        cls: "ai-chat-attach-remove",
        text: "\xD7",
        attr: { type: "button", title: t("common.remove_attach") }
      });
      rm.addEventListener("click", (e) => {
        e.stopPropagation();
        this.attachedNotes = this.attachedNotes.filter(
          (x) => x.path !== n.path
        );
        this.renderAttachedChips();
      });
    }
  }
  switchNote() {
    this.saveNote();
    this.noteKey = this.currentNote();
    this.loadNote();
  }
  /** 设置变更后刷新模型下拉 */
  refreshModels() {
    if (!this.modelSelect) return;
    this.populateModels();
    this.showUsage(null);
  }
  currentModel() {
    var _a;
    const id = (_a = this.modelSelect) == null ? void 0 : _a.value;
    return this.plugin.settings.models.find((m) => m.id === id) || this.plugin.settings.models[0];
  }
  populateModels() {
    this.modelSelect.empty();
    for (const m of this.plugin.settings.models) {
      this.modelSelect.createEl("option", { text: m.name, value: m.id });
    }
    if (this.plugin.settings.defaultModelId) {
      this.modelSelect.value = this.plugin.settings.defaultModelId;
    }
  }
  render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("ai-chat");
    const header = root.createDiv({ cls: "ai-chat-header" });
    this.modelSelect = header.createEl("select", {
      cls: "ai-chat-model-select dropdown"
    });
    this.populateModels();
    this.modelSelect.addEventListener("change", () => this.showUsage(null));
    const newBtn = header.createEl("button", {
      cls: "ai-chat-clear",
      attr: { type: "button", title: t("chat.new") }
    });
    (0, import_obsidian6.setIcon)(newBtn, "plus");
    newBtn.addEventListener("click", () => {
      this.histories.delete(this.noteKey);
      this.usageByNote.delete(this.noteKey);
      this.messages = [];
      this.sessionUsage = { prompt: 0, completion: 0, total: 0 };
      this.attachedNotes = [];
      this.renderAttachedChips();
      this.renderMessages();
      this.showUsage(null);
    });
    this.messagesEl = root.createDiv({ cls: "ai-chat-messages" });
    this.usageEl = root.createDiv({ cls: "ai-chat-usage" });
    this.showUsage(null);
    this.attachEl = root.createDiv({ cls: "ai-chat-attach" });
    this.renderAttachedChips();
    const inputWrap = root.createDiv({ cls: "ai-chat-input-wrap" });
    this.inputEl = inputWrap.createEl("textarea", {
      cls: "ai-chat-input",
      placeholder: t("chat.placeholder")
    });
    const sendBtn = inputWrap.createEl("button", {
      cls: "ai-chat-send",
      text: t("common.send")
    });
    sendBtn.addEventListener("click", () => void this.send());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.send();
      }
    });
    this.linkSuggest = new NoteLinkSuggest(
      this.app,
      this.inputEl,
      (file, m) => this.insertNoteRef(file, m)
    );
    this.renderMessages();
  }
  renderMessages() {
    this.messagesEl.empty();
    for (const m of this.messages) {
      const bubble = this.messagesEl.createDiv({
        cls: `ai-msg ai-msg-${m.role}`
      });
      bubble.createDiv({
        cls: "ai-msg-role",
        text: m.role === "user" ? t("common.you") : "AI"
      });
      bubble.createDiv({ cls: "ai-msg-content", text: m.content });
      const copyBtn = bubble.createEl("button", {
        cls: "ai-msg-copy",
        attr: { type: "button", title: t("common.copy") }
      });
      (0, import_obsidian6.setIcon)(copyBtn, "copy");
      copyBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        void copyText(m.content);
      });
      if (m.role === "user") {
        const editBtn = bubble.createEl("button", {
          cls: "ai-msg-edit",
          text: "\u270F\uFE0F",
          attr: { type: "button", title: t("common.edit_resend") }
        });
        editBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          const idx = this.messages.indexOf(m);
          this.messages = this.messages.slice(0, idx);
          this.inputEl.value = m.content;
          this.renderMessages();
          this.inputEl.focus();
        });
      }
    }
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  async send() {
    const text = this.inputEl.value.trim();
    if (!text || this.busy) return;
    const model = this.currentModel();
    if (!model) {
      new import_obsidian6.Notice(t("common.no_model"));
      return;
    }
    this.attachRefsFromText(text);
    this.inputEl.value = "";
    this.messages.push({ role: "user", content: text });
    this.renderMessages();
    await this.runAssistantTurn(model);
  }
  /** 从消息文本解析 [[笔记名]]：resolve 成功后加入关联列表，失败给出提示 */
  attachRefsFromText(text) {
    const re = /\[\[([^\]]+)\]\]/g;
    let m;
    let added = false;
    while ((m = re.exec(text)) !== null) {
      const name = m[1].trim();
      if (!name) continue;
      const f = this.resolveNote(name);
      if (!f) {
        new import_obsidian6.Notice(tf("chat.note_not_found", { name }));
        continue;
      }
      if (!this.attachedNotes.some((x) => x.path === f.path)) {
        this.attachedNotes.push({ path: f.path, basename: f.basename });
        added = true;
      }
    }
    if (added) this.renderAttachedChips();
  }
  /** [[X]] 补全选中：把 [[X]] 插入输入框并立即显示关联标签 */
  insertNoteRef(file, match) {
    const cur = this.inputEl.value;
    const insert = `[[${file.basename}]]`;
    this.inputEl.value = cur.slice(0, match.start) + insert + cur.slice(match.end);
    const pos = match.start + insert.length;
    this.inputEl.setSelectionRange(pos, pos);
    this.inputEl.focus();
    this.attachNote(file);
  }
  /** 把笔记加入关联列表并渲染标签（去重） */
  attachNote(file) {
    if (!this.attachedNotes.some((x) => x.path === file.path)) {
      this.attachedNotes.push({ path: file.path, basename: file.basename });
      this.renderAttachedChips();
    }
  }
  /** 打开 Chat 时把当前笔记自动加入关联标签（可见、可删） */
  autoAttachCurrentNote() {
    if (!this.noteKey || this.noteKey === "(\u65E0\u7B14\u8BB0)") return;
    const f = this.app.vault.getAbstractFileByPath(this.noteKey);
    if (f instanceof import_obsidian6.TFile) this.attachNote(f);
  }
  /** 解析 [[名称]]：wikilink/路径优先，其次按 basename 精确/模糊匹配（兜底） */
  resolveNote(name) {
    const direct = this.app.metadataCache.getFirstLinkpathDest(name, "") || this.app.vault.getAbstractFileByPath(name);
    if (direct instanceof import_obsidian6.TFile) return direct;
    const lower = name.toLowerCase();
    const files = this.app.vault.getMarkdownFiles();
    return files.find((f) => f.basename.toLowerCase() === lower) || files.find((f) => f.basename.toLowerCase().includes(lower)) || null;
  }
  /**
   * 流式生成 AI 回复。send 与「重新获取」共用。
   * 把输入框内已关联（可删除）的笔记内容作为上下文（system instruction）发给 AI。
   * 失败时在气泡上加「↻ 重新获取」按钮，点击重跑这一轮（不清空历史）。
   * 对所有供应商生效。
   */
  async runAssistantTurn(model) {
    this.busy = true;
    let acc = "";
    const aiBubble = this.messagesEl.createDiv({ cls: "ai-msg ai-msg-model" });
    const roleEl = aiBubble.createDiv({ cls: "ai-msg-role" });
    roleEl.createSpan({ cls: "ai-loading-spinner" });
    const contentEl = aiBubble.createDiv({
      cls: "ai-msg-content",
      text: ""
    });
    const copyBtn = aiBubble.createEl("button", {
      cls: "ai-msg-copy",
      attr: { type: "button", title: t("common.copy") }
    });
    (0, import_obsidian6.setIcon)(copyBtn, "copy");
    copyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void copyText(acc);
    });
    const provider = getProvider(model.provider);
    try {
      const sys = this.plugin.settings.systemInstruction;
      let noteCtx = "";
      if (this.attachedNotes.length > 0) {
        const blocks = [];
        for (const n of this.attachedNotes) {
          const f = this.app.vault.getAbstractFileByPath(n.path);
          if (!(f instanceof import_obsidian6.TFile)) continue;
          try {
            const content = await this.app.vault.cachedRead(f);
            blocks.push(`[[${n.basename}]]

${content}`);
          } catch (err) {
            console.warn("[Margin:chat] \u8BFB\u53D6\u5173\u8054\u7B14\u8BB0\u5931\u8D25", n.path, err);
          }
        }
        if (blocks.length > 0) {
          noteCtx += `

# ${t("chat.attached_notes")}
${blocks.join("\n\n---\n\n")}`;
        }
      }
      const systemInstruction = (sys ? sys + "\n\n" : "") + noteCtx;
      await provider.chat(
        model,
        this.messages,
        {
          onToken: (t2) => {
            acc += t2;
            contentEl.setText(acc);
            this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
          },
          onDone: (usage) => {
            roleEl.setText("AI");
            this.messages.push({ role: "model", content: acc });
            if (usage) {
              this.sessionUsage.prompt += usage.promptTokens;
              this.sessionUsage.completion += usage.completionTokens;
              this.sessionUsage.total += usage.totalTokens;
            }
            this.showUsage(usage);
          },
          onError: (e) => {
            console.error("[Margin:chat] chat error", e);
            roleEl.setText("AI");
            new import_obsidian6.Notice(t("common.error") + e.message);
            contentEl.setText("\u26A0\uFE0F " + e.message);
            const retryBtn = aiBubble.createEl("button", {
              cls: "ai-msg-retry",
              attr: { type: "button", title: t("common.retry") }
            });
            (0, import_obsidian6.setIcon)(retryBtn, "rotate-ccw");
            retryBtn.addEventListener("click", (ev) => {
              ev.stopPropagation();
              aiBubble.remove();
              const m = this.currentModel();
              if (!m) return;
              void this.runAssistantTurn(m);
            });
          }
        },
        { systemInstruction }
      );
    } finally {
      this.busy = false;
    }
  }
  /** 用量 / 模型限额。两行：上行模型+限额，下行会话+本次用量 */
  showUsage(u) {
    var _a;
    this.usageEl.empty();
    const m = this.currentModel();
    const limits = m ? modelLimitsText(m) : "";
    const row1 = this.usageEl.createDiv({ cls: "ai-chat-usage-line" });
    row1.setText(
      `${(_a = m == null ? void 0 : m.name) != null ? _a : t("common.no_model_selected")}${limits ? " \xB7 " + limits : ""}`
    );
    const row2 = this.usageEl.createDiv({ cls: "ai-chat-usage-line" });
    const s = this.sessionUsage;
    const tail = u ? tf("chat.this_usage", {
      prompt: u.promptTokens,
      completion: u.completionTokens,
      total: u.totalTokens
    }) : "\u2014";
    row2.setText(
      tf("chat.session_usage", {
        prompt: s.prompt,
        completion: s.completion,
        total: s.total,
        tail
      })
    );
  }
};

// src/selection/popover.ts
var import_obsidian7 = require("obsidian");
var Z_TOP = 2147483e3;
var _SelectionPopover = class _SelectionPopover {
  constructor(plugin, editor, selected) {
    __publicField(this, "plugin");
    __publicField(this, "editor");
    __publicField(this, "selected");
    __publicField(this, "messages", []);
    __publicField(this, "from");
    __publicField(this, "to");
    __publicField(this, "noteKey", "");
    __publicField(this, "root");
    __publicField(this, "messagesEl");
    __publicField(this, "inputEl");
    __publicField(this, "actionsEl");
    __publicField(this, "usageEl");
    __publicField(this, "lastResult", "");
    __publicField(this, "attachEl");
    __publicField(this, "attachedNotes", []);
    __publicField(this, "linkSuggest");
    __publicField(this, "busy", false);
    this.plugin = plugin;
    this.editor = editor;
    this.selected = selected;
    this.from = editor.getCursor("from");
    this.to = editor.getCursor("to");
  }
  open() {
    var _a, _b, _c;
    (_a = _SelectionPopover.current) == null ? void 0 : _a.close();
    _SelectionPopover.current = this;
    this.noteKey = (_c = (_b = this.plugin.app.workspace.getActiveFile()) == null ? void 0 : _b.path) != null ? _c : "";
    const root = document.body.createDiv({ cls: "ai-popover" });
    root.style.zIndex = String(Z_TOP);
    root.addEventListener("click", (e) => e.stopPropagation());
    const header = root.createDiv({ cls: "ai-popover-header" });
    const title = header.createSpan({ cls: "ai-popover-title", text: "Margin" });
    title.addClass("ai-popover-drag");
    const right = header.createDiv({ cls: "ai-popover-header-right" });
    const close = right.createEl("button", {
      cls: "ai-popover-close",
      attr: { type: "button", title: t("common.close") }
    });
    (0, import_obsidian7.setIcon)(close, "x");
    close.addEventListener("click", (e) => {
      e.stopPropagation();
      this.close();
    });
    if (this.selected) {
      const ctx = root.createDiv({ cls: "ai-popover-ctx" });
      ctx.createSpan({ cls: "ai-popover-ctx-label", text: t("popover.selection") });
      ctx.createSpan({
        cls: "ai-popover-ctx-text",
        text: this.selected.slice(0, 120) + (this.selected.length > 120 ? "\u2026" : "")
      });
    }
    this.messagesEl = root.createDiv({ cls: "ai-popover-messages" });
    this.usageEl = root.createDiv({ cls: "ai-popover-usage" });
    this.actionsEl = root.createDiv({ cls: "ai-popover-actions" });
    this.attachEl = root.createDiv({ cls: "ai-chat-attach" });
    this.renderAttachedChips();
    const inputWrap = root.createDiv({ cls: "ai-popover-input-wrap" });
    this.inputEl = inputWrap.createEl("textarea", {
      cls: "ai-popover-input",
      placeholder: this.selected ? t("popover.placeholder_sel") : t("popover.placeholder")
    });
    const send = inputWrap.createEl("button", {
      cls: "ai-popover-send",
      text: t("common.send")
    });
    send.addEventListener("click", () => void this.send());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.send();
      }
    });
    this.linkSuggest = new NoteLinkSuggest(
      this.plugin.app,
      this.inputEl,
      (file, m) => this.insertNoteRef(file, m)
    );
    this.root = root;
    this.renderMessages();
    this.renderActions();
    this.renderUsage(null);
    this.inputEl.focus();
    const rect = this.getSelectionRect();
    this.position(rect);
    this.makeDraggable(header);
  }
  getSelectionRect() {
    const sel = window.getSelection();
    if (sel && sel.rangeCount > 0) {
      const r = sel.getRangeAt(0).getBoundingClientRect();
      if (r && (r.width > 0 || r.height > 0)) return r;
    }
    return null;
  }
  position(rect) {
    if (!this.root) return;
    const w = Math.min(480, window.innerWidth - 16);
    const h = 420;
    let x = rect ? rect.left : window.innerWidth / 2 - w / 2;
    let y = rect ? rect.bottom + 8 : window.innerHeight / 2 - h / 2;
    x = Math.max(8, Math.min(x, window.innerWidth - w - 8));
    y = Math.max(8, Math.min(y, window.innerHeight - h - 8));
    this.root.style.width = w + "px";
    this.root.style.left = x + "px";
    this.root.style.top = y + "px";
  }
  makeDraggable(header) {
    let dragging = false;
    let startX = 0;
    let startY = 0;
    let origX = 0;
    let origY = 0;
    const isBtn = (t2) => {
      var _a;
      return !!((_a = t2 == null ? void 0 : t2.closest) == null ? void 0 : _a.call(t2, ".ai-popover-close"));
    };
    const begin = (cx, cy) => {
      var _a, _b, _c, _d;
      dragging = true;
      startX = cx;
      startY = cy;
      origX = (_b = (_a = this.root) == null ? void 0 : _a.offsetLeft) != null ? _b : 0;
      origY = (_d = (_c = this.root) == null ? void 0 : _c.offsetTop) != null ? _d : 0;
    };
    const move = (cx, cy) => {
      if (!dragging || !this.root) return;
      let x = origX + (cx - startX);
      let y = origY + (cy - startY);
      x = Math.max(0, Math.min(x, window.innerWidth - this.root.offsetWidth));
      y = Math.max(0, Math.min(y, window.innerHeight - this.root.offsetHeight));
      this.root.style.left = x + "px";
      this.root.style.top = y + "px";
    };
    const end = () => {
      dragging = false;
    };
    header.addEventListener("mousedown", (e) => {
      if (isBtn(e.target)) return;
      begin(e.clientX, e.clientY);
      e.preventDefault();
    });
    document.addEventListener("mousemove", (e) => move(e.clientX, e.clientY));
    document.addEventListener("mouseup", end);
    header.addEventListener("touchstart", (e) => {
      if (isBtn(e.target) || !e.touches[0]) return;
      begin(e.touches[0].clientX, e.touches[0].clientY);
      e.preventDefault();
    });
    document.addEventListener(
      "touchmove",
      (e) => {
        if (dragging && e.touches[0]) {
          move(e.touches[0].clientX, e.touches[0].clientY);
          e.preventDefault();
        }
      },
      { passive: false }
    );
    document.addEventListener("touchend", end);
  }
  /** 关闭悬浮窗（每次打开都是新对话，不保存） */
  close() {
    var _a;
    if (_SelectionPopover.current === this) _SelectionPopover.current = void 0;
    (_a = this.root) == null ? void 0 : _a.remove();
    this.root = void 0;
  }
  renderActions() {
    if (!this.actionsEl) return;
    this.actionsEl.empty();
    if (!this.lastResult) {
      this.actionsEl.setText("");
      return;
    }
    const mk = (label, iconId, fn) => {
      const b = this.actionsEl.createEl("button", {
        cls: "ai-popover-btn",
        attr: { type: "button", title: label }
      });
      (0, import_obsidian7.setIcon)(b, iconId);
      b.addEventListener("click", fn);
    };
    mk(t("popover.insert"), "corner-down-left", () => {
      this.editor.replaceRange(this.lastResult, this.editor.getCursor());
      new import_obsidian7.Notice(t("popover.inserted"));
    });
    mk(t("popover.overwrite"), "refresh-cw", () => {
      this.editor.replaceRange(this.lastResult, this.from, this.to);
      new import_obsidian7.Notice(t("popover.overwritten"));
    });
  }
  renderMessages() {
    if (!this.messagesEl) return;
    this.messagesEl.empty();
    for (const m of this.messages) {
      const text = this.displayText(m);
      const bubble = this.messagesEl.createDiv({
        cls: `ai-popover-msg ai-popover-msg-${m.role}`
      });
      bubble.createDiv({
        cls: "ai-popover-msg-role",
        text: m.role === "user" ? t("common.you") : "AI"
      });
      bubble.createDiv({ cls: "ai-popover-msg-content", text });
      const copyBtn = bubble.createEl("button", {
        cls: "ai-popover-msg-copy",
        attr: { type: "button", title: t("common.copy") }
      });
      (0, import_obsidian7.setIcon)(copyBtn, "copy");
      copyBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        void copyText(text);
      });
      if (m.role === "user") {
        const editBtn = bubble.createEl("button", {
          cls: "ai-popover-msg-edit",
          text: "\u270F\uFE0F",
          attr: { type: "button", title: t("common.edit_resend") }
        });
        editBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          this.editMessage(m);
        });
      }
    }
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  /** 首条带选区上下文的消息，展示时只显示问题本身 */
  displayText(m) {
    const marker = t("popover.ask_marker");
    const i = m.content.indexOf(marker);
    if (m.role === "user" && i >= 0) {
      return "\u{1F4CC} " + t("popover.selection_label") + m.content.slice(i + marker.length);
    }
    return m.content;
  }
  /** 编辑用户消息：截断到该条之前，把内容回填输入框重发 */
  editMessage(m) {
    const idx = this.messages.indexOf(m);
    if (idx < 0 || !this.inputEl) return;
    this.messages = this.messages.slice(0, idx);
    const prefix = "\u{1F4CC} " + t("popover.selection_label");
    let q = this.displayText(m);
    if (q.startsWith(prefix)) q = q.slice(prefix.length);
    this.inputEl.value = q;
    this.renderMessages();
    this.renderActions();
    this.inputEl.focus();
  }
  currentModel() {
    return this.plugin.settings.models.find(
      (m) => m.id === this.plugin.settings.defaultModelId
    ) || this.plugin.settings.models[0];
  }
  /** 渲染输入框内的关联笔记 chip（可删除） */
  renderAttachedChips() {
    if (!this.attachEl) return;
    this.attachEl.empty();
    if (this.attachedNotes.length === 0) return;
    for (const n of this.attachedNotes) {
      const chip = this.attachEl.createSpan({ cls: "ai-chat-attach-chip" });
      chip.createSpan({ text: "[[" + n.basename + "]]" });
      const rm = chip.createEl("button", {
        cls: "ai-chat-attach-remove",
        text: "\xD7",
        attr: { type: "button", title: t("common.remove_attach") }
      });
      rm.addEventListener("click", (e) => {
        e.stopPropagation();
        this.attachedNotes = this.attachedNotes.filter(
          (x) => x.path !== n.path
        );
        this.renderAttachedChips();
      });
    }
  }
  /** 从消息文本解析 [[笔记名]]：resolve 成功后加入关联列表，失败给出提示 */
  attachRefsFromText(text) {
    const re = /\[\[([^\]]+)\]\]/g;
    let m;
    let added = false;
    while ((m = re.exec(text)) !== null) {
      const name = m[1].trim();
      if (!name) continue;
      const f = this.resolveNote(name);
      if (!f) {
        new import_obsidian7.Notice(tf("chat.note_not_found", { name }));
        continue;
      }
      if (!this.attachedNotes.some((x) => x.path === f.path)) {
        this.attachedNotes.push({ path: f.path, basename: f.basename });
        added = true;
      }
    }
    if (added) this.renderAttachedChips();
  }
  /** [[X]] 补全选中：把 [[X]] 插入输入框并立即显示关联标签 */
  insertNoteRef(file, match) {
    if (!this.inputEl) return;
    const cur = this.inputEl.value;
    const insert = `[[${file.basename}]]`;
    this.inputEl.value = cur.slice(0, match.start) + insert + cur.slice(match.end);
    const pos = match.start + insert.length;
    this.inputEl.setSelectionRange(pos, pos);
    this.inputEl.focus();
    this.attachNote(file);
  }
  /** 把笔记加入关联列表并渲染标签（去重） */
  attachNote(file) {
    if (!this.attachedNotes.some((x) => x.path === file.path)) {
      this.attachedNotes.push({ path: file.path, basename: file.basename });
      this.renderAttachedChips();
    }
  }
  /** 解析 [[名称]]：wikilink/路径优先，其次按 basename 精确/模糊匹配（兜底） */
  resolveNote(name) {
    const direct = this.plugin.app.metadataCache.getFirstLinkpathDest(name, "") || this.plugin.app.vault.getAbstractFileByPath(name);
    if (direct instanceof import_obsidian7.TFile) return direct;
    const lower = name.toLowerCase();
    const files = this.plugin.app.vault.getMarkdownFiles();
    return files.find((f) => f.basename.toLowerCase() === lower) || files.find((f) => f.basename.toLowerCase().includes(lower)) || null;
  }
  async send() {
    var _a;
    const text = (_a = this.inputEl) == null ? void 0 : _a.value.trim();
    if (!text || this.busy) return;
    const model = this.currentModel();
    if (!model) {
      new import_obsidian7.Notice(t("common.no_model"));
      return;
    }
    this.attachRefsFromText(text);
    if (this.messages.length === 0) {
      if (this.selected) {
        this.messages.push({
          role: "user",
          content: tf("popover.ask_prompt", {
            selection: this.selected,
            question: text
          })
        });
      } else {
        this.messages.push({ role: "user", content: text });
      }
    } else {
      this.messages.push({ role: "user", content: text });
    }
    if (this.inputEl) this.inputEl.value = "";
    this.renderMessages();
    await this.runAssistantTurn(model);
  }
  /**
   * 流式生成 AI 回复。send 与「重新获取」共用。
   * 失败时在气泡上加「↻ 重新获取」按钮，点击重跑这一轮（用户消息已在 messages 中，不重置历史）。
   * 对所有供应商生效（UI 层重发，与 provider 无关）。
   */
  async runAssistantTurn(model) {
    this.busy = true;
    let acc = "";
    const aiBubble = this.messagesEl.createDiv({
      cls: "ai-popover-msg ai-popover-msg-model"
    });
    const roleEl = aiBubble.createDiv({ cls: "ai-popover-msg-role" });
    roleEl.createSpan({ cls: "ai-loading-spinner" });
    const contentEl = aiBubble.createDiv({
      cls: "ai-popover-msg-content",
      text: ""
    });
    const copyBtn = aiBubble.createEl("button", {
      cls: "ai-popover-msg-copy",
      attr: { type: "button", title: t("common.copy") }
    });
    (0, import_obsidian7.setIcon)(copyBtn, "copy");
    copyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void copyText(acc);
    });
    const provider = getProvider(model.provider);
    try {
      let noteCtx = "";
      if (this.attachedNotes.length > 0) {
        const blocks = [];
        for (const n of this.attachedNotes) {
          const f = this.plugin.app.vault.getAbstractFileByPath(n.path);
          if (!(f instanceof import_obsidian7.TFile)) continue;
          try {
            const content = await this.plugin.app.vault.cachedRead(f);
            blocks.push(`[[${n.basename}]]

${content}`);
          } catch (err) {
            console.warn("[Margin:popover] \u8BFB\u53D6\u5173\u8054\u7B14\u8BB0\u5931\u8D25", n.path, err);
          }
        }
        if (blocks.length > 0) {
          noteCtx = `

# ${t("chat.attached_notes")}
${blocks.join("\n\n---\n\n")}`;
        }
      }
      const sys = this.plugin.settings.systemInstruction;
      const systemInstruction = (sys ? sys + "\n\n" : "") + noteCtx;
      await provider.chat(
        model,
        this.messages,
        {
          onToken: (t2) => {
            acc += t2;
            contentEl.setText(acc);
            this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
          },
          onDone: (u) => {
            roleEl.setText("AI");
            this.messages.push({ role: "model", content: acc });
            this.lastResult = acc;
            this.renderActions();
            this.renderUsage(u);
          },
          onError: (e) => {
            console.error("[Margin:popover] chat error", e);
            roleEl.setText("AI");
            new import_obsidian7.Notice(t("common.error") + e.message);
            contentEl.setText("\u26A0\uFE0F " + e.message);
            const retryBtn = aiBubble.createEl("button", {
              cls: "ai-popover-msg-retry",
              attr: { type: "button", title: t("common.retry") }
            });
            (0, import_obsidian7.setIcon)(retryBtn, "rotate-ccw");
            retryBtn.addEventListener("click", (ev) => {
              ev.stopPropagation();
              aiBubble.remove();
              const m = this.currentModel();
              if (!m) return;
              void this.runAssistantTurn(m);
            });
          }
        },
        { systemInstruction }
      );
    } finally {
      this.busy = false;
    }
  }
  renderUsage(u) {
    if (!this.usageEl) return;
    this.usageEl.empty();
    const model = this.plugin.settings.models.find(
      (m) => m.id === this.plugin.settings.defaultModelId
    ) || this.plugin.settings.models[0];
    if (!model) {
      this.usageEl.setText(t("common.no_model_selected"));
      return;
    }
    const limits = modelLimitsText(model);
    const line1 = this.usageEl.createDiv({ cls: "ai-popover-usage-line" });
    line1.setText(`${model.name}${limits ? " \xB7 " + limits : ""}`);
    if (u) {
      const line2 = this.usageEl.createDiv({ cls: "ai-popover-usage-line" });
      line2.setText(
        tf("popover.this_usage", {
          prompt: u.promptTokens,
          completion: u.completionTokens,
          total: u.totalTokens
        })
      );
    }
  }
};
/** 同一时间只保留一个悬浮窗，避免多个叠加、卡在旧对话里 */
__publicField(_SelectionPopover, "current");
var SelectionPopover = _SelectionPopover;

// src/main.ts
var AIPlugin = class extends import_obsidian8.Plugin {
  async onload() {
    await this.loadSettings();
    setLang(detectObsidianLang());
    this.registerView(VIEW_TYPE_CHAT, (leaf) => new ChatView(leaf, this));
    this.addRibbonIcon("message-square", t("cmd.open_chat"), () => {
      void this.activateChat();
    });
    this.addCommand({
      id: "open-ai-chat",
      name: t("cmd.open_chat"),
      callback: () => void this.activateChat()
    });
    this.registerEvent(
      this.app.workspace.on(
        "editor-menu",
        (menu, editor) => {
          const selected = editor.getSelection();
          if (!selected) return;
          menu.addItem((item) => {
            item.setTitle("Margin").setIcon("sparkles").onClick(() => {
              const popover = new SelectionPopover(
                this,
                editor,
                selected
              );
              popover.open();
            });
          });
        }
      )
    );
    this.addSettingTab(new AISettingsTab(this.app, this));
    this.addCommand({
      id: "open-margin-popover",
      name: t("cmd.open_popover"),
      callback: () => {
        let view = this.app.workspace.getActiveViewOfType(import_obsidian8.MarkdownView);
        if (!view) {
          for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
            if (leaf.view instanceof import_obsidian8.MarkdownView) {
              view = leaf.view;
              break;
            }
          }
        }
        if (!view) {
          new import_obsidian8.Notice(t("popover.no_note"));
          return;
        }
        new SelectionPopover(this, view.editor, view.editor.getSelection()).open();
      }
    });
    this.registerEvent(
      this.app.workspace.on("margin:settings-changed", () => {
        const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
        if (leaf) leaf.view.refreshModels();
      })
    );
  }
  onunload() {
  }
  async activateChat() {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
    }
    void this.app.workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.app.workspace.trigger("margin:settings-changed");
  }
};
